// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AgentInitParameters struct {

	// Built-in agent configuration. Discriminated by `name`.
	BuiltInAgentConfig []BuiltInAgentConfigInitParameters `json:"builtInAgentConfig,omitempty" tf:"built_in_agent_config,omitempty"`

	// Knowledge connector IDs the agent has access to
	ConnectorIds []*string `json:"connectorIds,omitempty" tf:"connector_ids,omitempty"`

	// Whether the agent context is treated as untrusted
	ConsiderContextUntrusted *bool `json:"considerContextUntrusted,omitempty" tf:"consider_context_untrusted,omitempty"`

	// Human-readable description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Emoji or base64 image data URL
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// Allowed sender domain when `incoming_email_security_mode = "internal"`
	IncomingEmailAllowedDomain *string `json:"incomingEmailAllowedDomain,omitempty" tf:"incoming_email_allowed_domain,omitempty"`

	// Whether incoming-email invocation is enabled
	IncomingEmailEnabled *bool `json:"incomingEmailEnabled,omitempty" tf:"incoming_email_enabled,omitempty"`

	// Email-trigger security mode. One of `private` (only the agent owner can email it), `internal` (any sender from `incoming_email_allowed_domain` can), or `public` (any sender). Defaults to `private`.
	IncomingEmailSecurityMode *string `json:"incomingEmailSecurityMode,omitempty" tf:"incoming_email_security_mode,omitempty"`

	// Whether this is the default agent for its type
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// Knowledge base IDs the agent has access to
	KnowledgeBaseIds []*string `json:"knowledgeBaseIds,omitempty" tf:"knowledge_base_ids,omitempty"`

	Labels []LabelsInitParameters `json:"labels,omitempty" tf:"labels,omitempty"`

	// ID of the LLM provider API key the agent should use
	LlmAPIKeyID *string `json:"llmApiKeyId,omitempty" tf:"llm_api_key_id,omitempty"`

	// Model ID used for LLM calls
	LlmModel *string `json:"llmModel,omitempty" tf:"llm_model,omitempty"`

	// Agent name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Ownership scope: `personal`, `team`, or `org` (default: `org`).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	SuggestedPrompts []SuggestedPromptsInitParameters `json:"suggestedPrompts,omitempty" tf:"suggested_prompts,omitempty"`

	// System prompt that frames the agent's behavior
	SystemPrompt *string `json:"systemPrompt,omitempty" tf:"system_prompt,omitempty"`

	// Team IDs this agent is assigned to. Required when `scope = "team"`. Removing from configuration clears the assignment on next apply.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type AgentObservation struct {

	// Built-in agent configuration. Discriminated by `name`.
	BuiltInAgentConfig []BuiltInAgentConfigObservation `json:"builtInAgentConfig,omitempty" tf:"built_in_agent_config,omitempty"`

	// Knowledge connector IDs the agent has access to
	ConnectorIds []*string `json:"connectorIds,omitempty" tf:"connector_ids,omitempty"`

	// Whether the agent context is treated as untrusted
	ConsiderContextUntrusted *bool `json:"considerContextUntrusted,omitempty" tf:"consider_context_untrusted,omitempty"`

	// Human-readable description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Emoji or base64 image data URL
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// Allowed sender domain when `incoming_email_security_mode = "internal"`
	IncomingEmailAllowedDomain *string `json:"incomingEmailAllowedDomain,omitempty" tf:"incoming_email_allowed_domain,omitempty"`

	// Whether incoming-email invocation is enabled
	IncomingEmailEnabled *bool `json:"incomingEmailEnabled,omitempty" tf:"incoming_email_enabled,omitempty"`

	// Email-trigger security mode. One of `private` (only the agent owner can email it), `internal` (any sender from `incoming_email_allowed_domain` can), or `public` (any sender). Defaults to `private`.
	IncomingEmailSecurityMode *string `json:"incomingEmailSecurityMode,omitempty" tf:"incoming_email_security_mode,omitempty"`

	// Whether this is the default agent for its type
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// Knowledge base IDs the agent has access to
	KnowledgeBaseIds []*string `json:"knowledgeBaseIds,omitempty" tf:"knowledge_base_ids,omitempty"`

	Labels []LabelsObservation `json:"labels,omitempty" tf:"labels,omitempty"`

	// ID of the LLM provider API key the agent should use
	LlmAPIKeyID *string `json:"llmApiKeyId,omitempty" tf:"llm_api_key_id,omitempty"`

	// Model ID used for LLM calls
	LlmModel *string `json:"llmModel,omitempty" tf:"llm_model,omitempty"`

	// Agent name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Ownership scope: `personal`, `team`, or `org` (default: `org`).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	SuggestedPrompts []SuggestedPromptsObservation `json:"suggestedPrompts,omitempty" tf:"suggested_prompts,omitempty"`

	// System prompt that frames the agent's behavior
	SystemPrompt *string `json:"systemPrompt,omitempty" tf:"system_prompt,omitempty"`

	// Team IDs this agent is assigned to. Required when `scope = "team"`. Removing from configuration clears the assignment on next apply.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type AgentParameters struct {

	// Built-in agent configuration. Discriminated by `name`.
	// +kubebuilder:validation:Optional
	BuiltInAgentConfig []BuiltInAgentConfigParameters `json:"builtInAgentConfig,omitempty" tf:"built_in_agent_config,omitempty"`

	// Knowledge connector IDs the agent has access to
	// +kubebuilder:validation:Optional
	ConnectorIds []*string `json:"connectorIds,omitempty" tf:"connector_ids,omitempty"`

	// Whether the agent context is treated as untrusted
	// +kubebuilder:validation:Optional
	ConsiderContextUntrusted *bool `json:"considerContextUntrusted,omitempty" tf:"consider_context_untrusted,omitempty"`

	// Human-readable description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Emoji or base64 image data URL
	// +kubebuilder:validation:Optional
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// Allowed sender domain when `incoming_email_security_mode = "internal"`
	// +kubebuilder:validation:Optional
	IncomingEmailAllowedDomain *string `json:"incomingEmailAllowedDomain,omitempty" tf:"incoming_email_allowed_domain,omitempty"`

	// Whether incoming-email invocation is enabled
	// +kubebuilder:validation:Optional
	IncomingEmailEnabled *bool `json:"incomingEmailEnabled,omitempty" tf:"incoming_email_enabled,omitempty"`

	// Email-trigger security mode. One of `private` (only the agent owner can email it), `internal` (any sender from `incoming_email_allowed_domain` can), or `public` (any sender). Defaults to `private`.
	// +kubebuilder:validation:Optional
	IncomingEmailSecurityMode *string `json:"incomingEmailSecurityMode,omitempty" tf:"incoming_email_security_mode,omitempty"`

	// Whether this is the default agent for its type
	// +kubebuilder:validation:Optional
	IsDefault *bool `json:"isDefault,omitempty" tf:"is_default,omitempty"`

	// Knowledge base IDs the agent has access to
	// +kubebuilder:validation:Optional
	KnowledgeBaseIds []*string `json:"knowledgeBaseIds,omitempty" tf:"knowledge_base_ids,omitempty"`

	// +kubebuilder:validation:Optional
	Labels []LabelsParameters `json:"labels,omitempty" tf:"labels,omitempty"`

	// ID of the LLM provider API key the agent should use
	// +kubebuilder:validation:Optional
	LlmAPIKeyID *string `json:"llmApiKeyId,omitempty" tf:"llm_api_key_id,omitempty"`

	// Model ID used for LLM calls
	// +kubebuilder:validation:Optional
	LlmModel *string `json:"llmModel,omitempty" tf:"llm_model,omitempty"`

	// Agent name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Ownership scope: `personal`, `team`, or `org` (default: `org`).
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	SuggestedPrompts []SuggestedPromptsParameters `json:"suggestedPrompts,omitempty" tf:"suggested_prompts,omitempty"`

	// System prompt that frames the agent's behavior
	// +kubebuilder:validation:Optional
	SystemPrompt *string `json:"systemPrompt,omitempty" tf:"system_prompt,omitempty"`

	// Team IDs this agent is assigned to. Required when `scope = "team"`. Removing from configuration clears the assignment on next apply.
	// +kubebuilder:validation:Optional
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type BuiltInAgentConfigInitParameters struct {

	// Only applies when `name = "policy-configuration-subagent"`
	AutoConfigureOnToolDiscovery *bool `json:"autoConfigureOnToolDiscovery,omitempty" tf:"auto_configure_on_tool_discovery,omitempty"`

	// Only applies when `name = "dual-llm-main-agent"` (1–20)
	MaxRounds *float64 `json:"maxRounds,omitempty" tf:"max_rounds,omitempty"`

	// Built-in agent identifier: `policy-configuration-subagent`, `dual-llm-main-agent`, `dual-llm-quarantine-agent`
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type BuiltInAgentConfigObservation struct {

	// Only applies when `name = "policy-configuration-subagent"`
	AutoConfigureOnToolDiscovery *bool `json:"autoConfigureOnToolDiscovery,omitempty" tf:"auto_configure_on_tool_discovery,omitempty"`

	// Only applies when `name = "dual-llm-main-agent"` (1–20)
	MaxRounds *float64 `json:"maxRounds,omitempty" tf:"max_rounds,omitempty"`

	// Built-in agent identifier: `policy-configuration-subagent`, `dual-llm-main-agent`, `dual-llm-quarantine-agent`
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type BuiltInAgentConfigParameters struct {

	// Only applies when `name = "policy-configuration-subagent"`
	// +kubebuilder:validation:Optional
	AutoConfigureOnToolDiscovery *bool `json:"autoConfigureOnToolDiscovery,omitempty" tf:"auto_configure_on_tool_discovery,omitempty"`

	// Only applies when `name = "dual-llm-main-agent"` (1–20)
	// +kubebuilder:validation:Optional
	MaxRounds *float64 `json:"maxRounds,omitempty" tf:"max_rounds,omitempty"`

	// Built-in agent identifier: `policy-configuration-subagent`, `dual-llm-main-agent`, `dual-llm-quarantine-agent`
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type LabelsInitParameters struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LabelsObservation struct {
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LabelsParameters struct {

	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type SuggestedPromptsInitParameters struct {

	// Prompt text
	Prompt *string `json:"prompt,omitempty" tf:"prompt,omitempty"`

	// Title shown above the prompt
	SummaryTitle *string `json:"summaryTitle,omitempty" tf:"summary_title,omitempty"`
}

type SuggestedPromptsObservation struct {

	// Prompt text
	Prompt *string `json:"prompt,omitempty" tf:"prompt,omitempty"`

	// Title shown above the prompt
	SummaryTitle *string `json:"summaryTitle,omitempty" tf:"summary_title,omitempty"`
}

type SuggestedPromptsParameters struct {

	// Prompt text
	// +kubebuilder:validation:Optional
	Prompt *string `json:"prompt" tf:"prompt,omitempty"`

	// Title shown above the prompt
	// +kubebuilder:validation:Optional
	SummaryTitle *string `json:"summaryTitle" tf:"summary_title,omitempty"`
}

// AgentSpec defines the desired state of Agent
type AgentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AgentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AgentInitParameters `json:"initProvider,omitempty"`
}

// AgentStatus defines the observed state of Agent.
type AgentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AgentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Agent is the Schema for the Agents API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,archestra}
type Agent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AgentSpec   `json:"spec"`
	Status AgentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AgentList contains a list of Agents
type AgentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Agent `json:"items"`
}

// Repository type metadata.
var (
	Agent_Kind             = "Agent"
	Agent_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Agent_Kind}.String()
	Agent_KindAPIVersion   = Agent_Kind + "." + CRDGroupVersion.String()
	Agent_GroupVersionKind = CRDGroupVersion.WithKind(Agent_Kind)
)

func init() {
	SchemeBuilder.Register(&Agent{}, &AgentList{})
}
