// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/archestra-ai/provider-archestra/apis/namespaced/mcp/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ToolBatch.
func (mg *ToolBatch) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AgentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AgentIDRef,
		Selector:     mg.Spec.ForProvider.AgentIDSelector,
		To: reference.To{
			List:    &AgentList{},
			Managed: &Agent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AgentID")
	}
	mg.Spec.ForProvider.AgentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AgentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.McpServerID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.McpServerIDRef,
		Selector:     mg.Spec.ForProvider.McpServerIDSelector,
		To: reference.To{
			List:    &v1alpha1.ServerInstallationList{},
			Managed: &v1alpha1.ServerInstallation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.McpServerID")
	}
	mg.Spec.ForProvider.McpServerID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.McpServerIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AgentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AgentIDRef,
		Selector:     mg.Spec.InitProvider.AgentIDSelector,
		To: reference.To{
			List:    &AgentList{},
			Managed: &Agent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AgentID")
	}
	mg.Spec.InitProvider.AgentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AgentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.McpServerID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.McpServerIDRef,
		Selector:     mg.Spec.InitProvider.McpServerIDSelector,
		To: reference.To{
			List:    &v1alpha1.ServerInstallationList{},
			Managed: &v1alpha1.ServerInstallation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.McpServerID")
	}
	mg.Spec.InitProvider.McpServerID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.McpServerIDRef = rsp.ResolvedReference

	return nil
}
