version: 2
updates:
  - package-ecosystem: gomod
    directory: .
    schedule:
      interval: weekly
    groups:
      terraform-go-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
    commit-message:
      prefix: deps(terraform)

  - package-ecosystem: github-actions
    directory: .github
    groups:
      github-actions-dependencies:
        patterns:
          - "*.yml"
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: deps
