//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignedAgentsInitParameters) DeepCopyInto(out *AssignedAgentsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignedAgentsInitParameters.
func (in *AssignedAgentsInitParameters) DeepCopy() *AssignedAgentsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AssignedAgentsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignedAgentsObservation) DeepCopyInto(out *AssignedAgentsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignedAgentsObservation.
func (in *AssignedAgentsObservation) DeepCopy() *AssignedAgentsObservation {
	if in == nil {
		return nil
	}
	out := new(AssignedAgentsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssignedAgentsParameters) DeepCopyInto(out *AssignedAgentsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssignedAgentsParameters.
func (in *AssignedAgentsParameters) DeepCopy() *AssignedAgentsParameters {
	if in == nil {
		return nil
	}
	out := new(AssignedAgentsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthFieldsInitParameters) DeepCopyInto(out *AuthFieldsInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthFieldsInitParameters.
func (in *AuthFieldsInitParameters) DeepCopy() *AuthFieldsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthFieldsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthFieldsObservation) DeepCopyInto(out *AuthFieldsObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthFieldsObservation.
func (in *AuthFieldsObservation) DeepCopy() *AuthFieldsObservation {
	if in == nil {
		return nil
	}
	out := new(AuthFieldsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthFieldsParameters) DeepCopyInto(out *AuthFieldsParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthFieldsParameters.
func (in *AuthFieldsParameters) DeepCopy() *AuthFieldsParameters {
	if in == nil {
		return nil
	}
	out := new(AuthFieldsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseManagedConfigInitParameters) DeepCopyInto(out *EnterpriseManagedConfigInitParameters) {
	*out = *in
	if in.AssertionMode != nil {
		in, out := &in.AssertionMode, &out.AssertionMode
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.BodyFieldName != nil {
		in, out := &in.BodyFieldName, &out.BodyFieldName
		*out = new(string)
		**out = **in
	}
	if in.CacheTTLSeconds != nil {
		in, out := &in.CacheTTLSeconds, &out.CacheTTLSeconds
		*out = new(float64)
		**out = **in
	}
	if in.ClientIDOverride != nil {
		in, out := &in.ClientIDOverride, &out.ClientIDOverride
		*out = new(string)
		**out = **in
	}
	if in.EnvVarName != nil {
		in, out := &in.EnvVarName, &out.EnvVarName
		*out = new(string)
		**out = **in
	}
	if in.FallbackMode != nil {
		in, out := &in.FallbackMode, &out.FallbackMode
		*out = new(string)
		**out = **in
	}
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.IdentityProviderID != nil {
		in, out := &in.IdentityProviderID, &out.IdentityProviderID
		*out = new(string)
		**out = **in
	}
	if in.RequestedCredentialType != nil {
		in, out := &in.RequestedCredentialType, &out.RequestedCredentialType
		*out = new(string)
		**out = **in
	}
	if in.RequestedIssuer != nil {
		in, out := &in.RequestedIssuer, &out.RequestedIssuer
		*out = new(string)
		**out = **in
	}
	if in.ResourceIdentifier != nil {
		in, out := &in.ResourceIdentifier, &out.ResourceIdentifier
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.ResponseFieldPath != nil {
		in, out := &in.ResponseFieldPath, &out.ResponseFieldPath
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TokenInjectionMode != nil {
		in, out := &in.TokenInjectionMode, &out.TokenInjectionMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseManagedConfigInitParameters.
func (in *EnterpriseManagedConfigInitParameters) DeepCopy() *EnterpriseManagedConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseManagedConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseManagedConfigObservation) DeepCopyInto(out *EnterpriseManagedConfigObservation) {
	*out = *in
	if in.AssertionMode != nil {
		in, out := &in.AssertionMode, &out.AssertionMode
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.BodyFieldName != nil {
		in, out := &in.BodyFieldName, &out.BodyFieldName
		*out = new(string)
		**out = **in
	}
	if in.CacheTTLSeconds != nil {
		in, out := &in.CacheTTLSeconds, &out.CacheTTLSeconds
		*out = new(float64)
		**out = **in
	}
	if in.ClientIDOverride != nil {
		in, out := &in.ClientIDOverride, &out.ClientIDOverride
		*out = new(string)
		**out = **in
	}
	if in.EnvVarName != nil {
		in, out := &in.EnvVarName, &out.EnvVarName
		*out = new(string)
		**out = **in
	}
	if in.FallbackMode != nil {
		in, out := &in.FallbackMode, &out.FallbackMode
		*out = new(string)
		**out = **in
	}
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.IdentityProviderID != nil {
		in, out := &in.IdentityProviderID, &out.IdentityProviderID
		*out = new(string)
		**out = **in
	}
	if in.RequestedCredentialType != nil {
		in, out := &in.RequestedCredentialType, &out.RequestedCredentialType
		*out = new(string)
		**out = **in
	}
	if in.RequestedIssuer != nil {
		in, out := &in.RequestedIssuer, &out.RequestedIssuer
		*out = new(string)
		**out = **in
	}
	if in.ResourceIdentifier != nil {
		in, out := &in.ResourceIdentifier, &out.ResourceIdentifier
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.ResponseFieldPath != nil {
		in, out := &in.ResponseFieldPath, &out.ResponseFieldPath
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TokenInjectionMode != nil {
		in, out := &in.TokenInjectionMode, &out.TokenInjectionMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseManagedConfigObservation.
func (in *EnterpriseManagedConfigObservation) DeepCopy() *EnterpriseManagedConfigObservation {
	if in == nil {
		return nil
	}
	out := new(EnterpriseManagedConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseManagedConfigParameters) DeepCopyInto(out *EnterpriseManagedConfigParameters) {
	*out = *in
	if in.AssertionMode != nil {
		in, out := &in.AssertionMode, &out.AssertionMode
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.BodyFieldName != nil {
		in, out := &in.BodyFieldName, &out.BodyFieldName
		*out = new(string)
		**out = **in
	}
	if in.CacheTTLSeconds != nil {
		in, out := &in.CacheTTLSeconds, &out.CacheTTLSeconds
		*out = new(float64)
		**out = **in
	}
	if in.ClientIDOverride != nil {
		in, out := &in.ClientIDOverride, &out.ClientIDOverride
		*out = new(string)
		**out = **in
	}
	if in.EnvVarName != nil {
		in, out := &in.EnvVarName, &out.EnvVarName
		*out = new(string)
		**out = **in
	}
	if in.FallbackMode != nil {
		in, out := &in.FallbackMode, &out.FallbackMode
		*out = new(string)
		**out = **in
	}
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.IdentityProviderID != nil {
		in, out := &in.IdentityProviderID, &out.IdentityProviderID
		*out = new(string)
		**out = **in
	}
	if in.RequestedCredentialType != nil {
		in, out := &in.RequestedCredentialType, &out.RequestedCredentialType
		*out = new(string)
		**out = **in
	}
	if in.RequestedIssuer != nil {
		in, out := &in.RequestedIssuer, &out.RequestedIssuer
		*out = new(string)
		**out = **in
	}
	if in.ResourceIdentifier != nil {
		in, out := &in.ResourceIdentifier, &out.ResourceIdentifier
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.ResponseFieldPath != nil {
		in, out := &in.ResponseFieldPath, &out.ResponseFieldPath
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TokenInjectionMode != nil {
		in, out := &in.TokenInjectionMode, &out.TokenInjectionMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseManagedConfigParameters.
func (in *EnterpriseManagedConfigParameters) DeepCopy() *EnterpriseManagedConfigParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseManagedConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvFromInitParameters) DeepCopyInto(out *EnvFromInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvFromInitParameters.
func (in *EnvFromInitParameters) DeepCopy() *EnvFromInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvFromInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvFromObservation) DeepCopyInto(out *EnvFromObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvFromObservation.
func (in *EnvFromObservation) DeepCopy() *EnvFromObservation {
	if in == nil {
		return nil
	}
	out := new(EnvFromObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvFromParameters) DeepCopyInto(out *EnvFromParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvFromParameters.
func (in *EnvFromParameters) DeepCopy() *EnvFromParameters {
	if in == nil {
		return nil
	}
	out := new(EnvFromParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentInitParameters) DeepCopyInto(out *EnvironmentInitParameters) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Mounted != nil {
		in, out := &in.Mounted, &out.Mounted
		*out = new(bool)
		**out = **in
	}
	if in.PromptOnInstallation != nil {
		in, out := &in.PromptOnInstallation, &out.PromptOnInstallation
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentInitParameters.
func (in *EnvironmentInitParameters) DeepCopy() *EnvironmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentObservation) DeepCopyInto(out *EnvironmentObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Mounted != nil {
		in, out := &in.Mounted, &out.Mounted
		*out = new(bool)
		**out = **in
	}
	if in.PromptOnInstallation != nil {
		in, out := &in.PromptOnInstallation, &out.PromptOnInstallation
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentObservation.
func (in *EnvironmentObservation) DeepCopy() *EnvironmentObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentParameters) DeepCopyInto(out *EnvironmentParameters) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Mounted != nil {
		in, out := &in.Mounted, &out.Mounted
		*out = new(bool)
		**out = **in
	}
	if in.PromptOnInstallation != nil {
		in, out := &in.PromptOnInstallation, &out.PromptOnInstallation
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentParameters.
func (in *EnvironmentParameters) DeepCopy() *EnvironmentParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretsInitParameters) DeepCopyInto(out *ImagePullSecretsInitParameters) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretsInitParameters.
func (in *ImagePullSecretsInitParameters) DeepCopy() *ImagePullSecretsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretsObservation) DeepCopyInto(out *ImagePullSecretsObservation) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretsObservation.
func (in *ImagePullSecretsObservation) DeepCopy() *ImagePullSecretsObservation {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretsParameters) DeepCopyInto(out *ImagePullSecretsParameters) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretsParameters.
func (in *ImagePullSecretsParameters) DeepCopy() *ImagePullSecretsParameters {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelsInitParameters) DeepCopyInto(out *LabelsInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelsInitParameters.
func (in *LabelsInitParameters) DeepCopy() *LabelsInitParameters {
	if in == nil {
		return nil
	}
	out := new(LabelsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelsObservation) DeepCopyInto(out *LabelsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelsObservation.
func (in *LabelsObservation) DeepCopy() *LabelsObservation {
	if in == nil {
		return nil
	}
	out := new(LabelsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelsParameters) DeepCopyInto(out *LabelsParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelsParameters.
func (in *LabelsParameters) DeepCopy() *LabelsParameters {
	if in == nil {
		return nil
	}
	out := new(LabelsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalConfigInitParameters) DeepCopyInto(out *LocalConfigInitParameters) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = new(string)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]EnvFromInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]EnvironmentInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTPPath != nil {
		in, out := &in.HTTPPath, &out.HTTPPath
		*out = new(string)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ImagePullSecretsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(float64)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TransportType != nil {
		in, out := &in.TransportType, &out.TransportType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalConfigInitParameters.
func (in *LocalConfigInitParameters) DeepCopy() *LocalConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(LocalConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalConfigObservation) DeepCopyInto(out *LocalConfigObservation) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = new(string)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]EnvFromObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]EnvironmentObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTPPath != nil {
		in, out := &in.HTTPPath, &out.HTTPPath
		*out = new(string)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ImagePullSecretsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(float64)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TransportType != nil {
		in, out := &in.TransportType, &out.TransportType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalConfigObservation.
func (in *LocalConfigObservation) DeepCopy() *LocalConfigObservation {
	if in == nil {
		return nil
	}
	out := new(LocalConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalConfigParameters) DeepCopyInto(out *LocalConfigParameters) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = new(string)
		**out = **in
	}
	if in.DockerImage != nil {
		in, out := &in.DockerImage, &out.DockerImage
		*out = new(string)
		**out = **in
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]EnvFromParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]EnvironmentParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HTTPPath != nil {
		in, out := &in.HTTPPath, &out.HTTPPath
		*out = new(string)
		**out = **in
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ImagePullSecretsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(float64)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TransportType != nil {
		in, out := &in.TransportType, &out.TransportType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalConfigParameters.
func (in *LocalConfigParameters) DeepCopy() *LocalConfigParameters {
	if in == nil {
		return nil
	}
	out := new(LocalConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OauthConfigInitParameters) DeepCopyInto(out *OauthConfigInitParameters) {
	*out = *in
	if in.AccessTokenEnvVar != nil {
		in, out := &in.AccessTokenEnvVar, &out.AccessTokenEnvVar
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.AuthServerURL != nil {
		in, out := &in.AuthServerURL, &out.AuthServerURL
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationEndpoint != nil {
		in, out := &in.AuthorizationEndpoint, &out.AuthorizationEndpoint
		*out = new(string)
		**out = **in
	}
	if in.BrowserAuth != nil {
		in, out := &in.BrowserAuth, &out.BrowserAuth
		*out = new(bool)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.DefaultScopes != nil {
		in, out := &in.DefaultScopes, &out.DefaultScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GenericOauth != nil {
		in, out := &in.GenericOauth, &out.GenericOauth
		*out = new(bool)
		**out = **in
	}
	if in.GrantType != nil {
		in, out := &in.GrantType, &out.GrantType
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RequiresProxy != nil {
		in, out := &in.RequiresProxy, &out.RequiresProxy
		*out = new(bool)
		**out = **in
	}
	if in.ResourceMetadataURL != nil {
		in, out := &in.ResourceMetadataURL, &out.ResourceMetadataURL
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StreamableHTTPPort != nil {
		in, out := &in.StreamableHTTPPort, &out.StreamableHTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.StreamableHTTPURL != nil {
		in, out := &in.StreamableHTTPURL, &out.StreamableHTTPURL
		*out = new(string)
		**out = **in
	}
	if in.SupportsResourceMetadata != nil {
		in, out := &in.SupportsResourceMetadata, &out.SupportsResourceMetadata
		*out = new(bool)
		**out = **in
	}
	if in.TokenEndpoint != nil {
		in, out := &in.TokenEndpoint, &out.TokenEndpoint
		*out = new(string)
		**out = **in
	}
	if in.WellKnownURL != nil {
		in, out := &in.WellKnownURL, &out.WellKnownURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OauthConfigInitParameters.
func (in *OauthConfigInitParameters) DeepCopy() *OauthConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(OauthConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OauthConfigObservation) DeepCopyInto(out *OauthConfigObservation) {
	*out = *in
	if in.AccessTokenEnvVar != nil {
		in, out := &in.AccessTokenEnvVar, &out.AccessTokenEnvVar
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.AuthServerURL != nil {
		in, out := &in.AuthServerURL, &out.AuthServerURL
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationEndpoint != nil {
		in, out := &in.AuthorizationEndpoint, &out.AuthorizationEndpoint
		*out = new(string)
		**out = **in
	}
	if in.BrowserAuth != nil {
		in, out := &in.BrowserAuth, &out.BrowserAuth
		*out = new(bool)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.DefaultScopes != nil {
		in, out := &in.DefaultScopes, &out.DefaultScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GenericOauth != nil {
		in, out := &in.GenericOauth, &out.GenericOauth
		*out = new(bool)
		**out = **in
	}
	if in.GrantType != nil {
		in, out := &in.GrantType, &out.GrantType
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RequiresProxy != nil {
		in, out := &in.RequiresProxy, &out.RequiresProxy
		*out = new(bool)
		**out = **in
	}
	if in.ResourceMetadataURL != nil {
		in, out := &in.ResourceMetadataURL, &out.ResourceMetadataURL
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StreamableHTTPPort != nil {
		in, out := &in.StreamableHTTPPort, &out.StreamableHTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.StreamableHTTPURL != nil {
		in, out := &in.StreamableHTTPURL, &out.StreamableHTTPURL
		*out = new(string)
		**out = **in
	}
	if in.SupportsResourceMetadata != nil {
		in, out := &in.SupportsResourceMetadata, &out.SupportsResourceMetadata
		*out = new(bool)
		**out = **in
	}
	if in.TokenEndpoint != nil {
		in, out := &in.TokenEndpoint, &out.TokenEndpoint
		*out = new(string)
		**out = **in
	}
	if in.WellKnownURL != nil {
		in, out := &in.WellKnownURL, &out.WellKnownURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OauthConfigObservation.
func (in *OauthConfigObservation) DeepCopy() *OauthConfigObservation {
	if in == nil {
		return nil
	}
	out := new(OauthConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OauthConfigParameters) DeepCopyInto(out *OauthConfigParameters) {
	*out = *in
	if in.AccessTokenEnvVar != nil {
		in, out := &in.AccessTokenEnvVar, &out.AccessTokenEnvVar
		*out = new(string)
		**out = **in
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(string)
		**out = **in
	}
	if in.AuthServerURL != nil {
		in, out := &in.AuthServerURL, &out.AuthServerURL
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationEndpoint != nil {
		in, out := &in.AuthorizationEndpoint, &out.AuthorizationEndpoint
		*out = new(string)
		**out = **in
	}
	if in.BrowserAuth != nil {
		in, out := &in.BrowserAuth, &out.BrowserAuth
		*out = new(bool)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.DefaultScopes != nil {
		in, out := &in.DefaultScopes, &out.DefaultScopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GenericOauth != nil {
		in, out := &in.GenericOauth, &out.GenericOauth
		*out = new(bool)
		**out = **in
	}
	if in.GrantType != nil {
		in, out := &in.GrantType, &out.GrantType
		*out = new(string)
		**out = **in
	}
	if in.ProviderName != nil {
		in, out := &in.ProviderName, &out.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.RedirectUris != nil {
		in, out := &in.RedirectUris, &out.RedirectUris
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RequiresProxy != nil {
		in, out := &in.RequiresProxy, &out.RequiresProxy
		*out = new(bool)
		**out = **in
	}
	if in.ResourceMetadataURL != nil {
		in, out := &in.ResourceMetadataURL, &out.ResourceMetadataURL
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StreamableHTTPPort != nil {
		in, out := &in.StreamableHTTPPort, &out.StreamableHTTPPort
		*out = new(float64)
		**out = **in
	}
	if in.StreamableHTTPURL != nil {
		in, out := &in.StreamableHTTPURL, &out.StreamableHTTPURL
		*out = new(string)
		**out = **in
	}
	if in.SupportsResourceMetadata != nil {
		in, out := &in.SupportsResourceMetadata, &out.SupportsResourceMetadata
		*out = new(bool)
		**out = **in
	}
	if in.TokenEndpoint != nil {
		in, out := &in.TokenEndpoint, &out.TokenEndpoint
		*out = new(string)
		**out = **in
	}
	if in.WellKnownURL != nil {
		in, out := &in.WellKnownURL, &out.WellKnownURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OauthConfigParameters.
func (in *OauthConfigParameters) DeepCopy() *OauthConfigParameters {
	if in == nil {
		return nil
	}
	out := new(OauthConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCatalogItem) DeepCopyInto(out *RegistryCatalogItem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCatalogItem.
func (in *RegistryCatalogItem) DeepCopy() *RegistryCatalogItem {
	if in == nil {
		return nil
	}
	out := new(RegistryCatalogItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryCatalogItem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCatalogItemInitParameters) DeepCopyInto(out *RegistryCatalogItemInitParameters) {
	*out = *in
	if in.AuthDescription != nil {
		in, out := &in.AuthDescription, &out.AuthDescription
		*out = new(string)
		**out = **in
	}
	if in.AuthFields != nil {
		in, out := &in.AuthFields, &out.AuthFields
		*out = make([]AuthFieldsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientSecretID != nil {
		in, out := &in.ClientSecretID, &out.ClientSecretID
		*out = new(string)
		**out = **in
	}
	if in.DeploymentSpecYaml != nil {
		in, out := &in.DeploymentSpecYaml, &out.DeploymentSpecYaml
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DocsURL != nil {
		in, out := &in.DocsURL, &out.DocsURL
		*out = new(string)
		**out = **in
	}
	if in.EnterpriseManagedConfig != nil {
		in, out := &in.EnterpriseManagedConfig, &out.EnterpriseManagedConfig
		*out = new(EnterpriseManagedConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.InstallationCommand != nil {
		in, out := &in.InstallationCommand, &out.InstallationCommand
		*out = new(string)
		**out = **in
	}
	if in.Instructions != nil {
		in, out := &in.Instructions, &out.Instructions
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]LabelsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LocalConfig != nil {
		in, out := &in.LocalConfig, &out.LocalConfig
		*out = new(LocalConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalConfigSecretID != nil {
		in, out := &in.LocalConfigSecretID, &out.LocalConfigSecretID
		*out = new(string)
		**out = **in
	}
	if in.LocalConfigVaultKey != nil {
		in, out := &in.LocalConfigVaultKey, &out.LocalConfigVaultKey
		*out = new(string)
		**out = **in
	}
	if in.LocalConfigVaultPath != nil {
		in, out := &in.LocalConfigVaultPath, &out.LocalConfigVaultPath
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthClientSecretVaultKey != nil {
		in, out := &in.OauthClientSecretVaultKey, &out.OauthClientSecretVaultKey
		*out = new(string)
		**out = **in
	}
	if in.OauthClientSecretVaultPath != nil {
		in, out := &in.OauthClientSecretVaultPath, &out.OauthClientSecretVaultPath
		*out = new(string)
		**out = **in
	}
	if in.RemoteConfig != nil {
		in, out := &in.RemoteConfig, &out.RemoteConfig
		*out = new(RemoteConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RequiresAuth != nil {
		in, out := &in.RequiresAuth, &out.RequiresAuth
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserConfig != nil {
		in, out := &in.UserConfig, &out.UserConfig
		*out = make(map[string]UserConfigInitParameters, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCatalogItemInitParameters.
func (in *RegistryCatalogItemInitParameters) DeepCopy() *RegistryCatalogItemInitParameters {
	if in == nil {
		return nil
	}
	out := new(RegistryCatalogItemInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCatalogItemList) DeepCopyInto(out *RegistryCatalogItemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RegistryCatalogItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCatalogItemList.
func (in *RegistryCatalogItemList) DeepCopy() *RegistryCatalogItemList {
	if in == nil {
		return nil
	}
	out := new(RegistryCatalogItemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryCatalogItemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCatalogItemObservation) DeepCopyInto(out *RegistryCatalogItemObservation) {
	*out = *in
	if in.AuthDescription != nil {
		in, out := &in.AuthDescription, &out.AuthDescription
		*out = new(string)
		**out = **in
	}
	if in.AuthFields != nil {
		in, out := &in.AuthFields, &out.AuthFields
		*out = make([]AuthFieldsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientSecretID != nil {
		in, out := &in.ClientSecretID, &out.ClientSecretID
		*out = new(string)
		**out = **in
	}
	if in.DeploymentSpecYaml != nil {
		in, out := &in.DeploymentSpecYaml, &out.DeploymentSpecYaml
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DocsURL != nil {
		in, out := &in.DocsURL, &out.DocsURL
		*out = new(string)
		**out = **in
	}
	if in.EnterpriseManagedConfig != nil {
		in, out := &in.EnterpriseManagedConfig, &out.EnterpriseManagedConfig
		*out = new(EnterpriseManagedConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.InstallationCommand != nil {
		in, out := &in.InstallationCommand, &out.InstallationCommand
		*out = new(string)
		**out = **in
	}
	if in.Instructions != nil {
		in, out := &in.Instructions, &out.Instructions
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]LabelsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LocalConfig != nil {
		in, out := &in.LocalConfig, &out.LocalConfig
		*out = new(LocalConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalConfigSecretID != nil {
		in, out := &in.LocalConfigSecretID, &out.LocalConfigSecretID
		*out = new(string)
		**out = **in
	}
	if in.LocalConfigVaultKey != nil {
		in, out := &in.LocalConfigVaultKey, &out.LocalConfigVaultKey
		*out = new(string)
		**out = **in
	}
	if in.LocalConfigVaultPath != nil {
		in, out := &in.LocalConfigVaultPath, &out.LocalConfigVaultPath
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthClientSecretVaultKey != nil {
		in, out := &in.OauthClientSecretVaultKey, &out.OauthClientSecretVaultKey
		*out = new(string)
		**out = **in
	}
	if in.OauthClientSecretVaultPath != nil {
		in, out := &in.OauthClientSecretVaultPath, &out.OauthClientSecretVaultPath
		*out = new(string)
		**out = **in
	}
	if in.RemoteConfig != nil {
		in, out := &in.RemoteConfig, &out.RemoteConfig
		*out = new(RemoteConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RequiresAuth != nil {
		in, out := &in.RequiresAuth, &out.RequiresAuth
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserConfig != nil {
		in, out := &in.UserConfig, &out.UserConfig
		*out = make(map[string]UserConfigObservation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCatalogItemObservation.
func (in *RegistryCatalogItemObservation) DeepCopy() *RegistryCatalogItemObservation {
	if in == nil {
		return nil
	}
	out := new(RegistryCatalogItemObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCatalogItemParameters) DeepCopyInto(out *RegistryCatalogItemParameters) {
	*out = *in
	if in.AuthDescription != nil {
		in, out := &in.AuthDescription, &out.AuthDescription
		*out = new(string)
		**out = **in
	}
	if in.AuthFields != nil {
		in, out := &in.AuthFields, &out.AuthFields
		*out = make([]AuthFieldsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientSecretID != nil {
		in, out := &in.ClientSecretID, &out.ClientSecretID
		*out = new(string)
		**out = **in
	}
	if in.DeploymentSpecYaml != nil {
		in, out := &in.DeploymentSpecYaml, &out.DeploymentSpecYaml
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DocsURL != nil {
		in, out := &in.DocsURL, &out.DocsURL
		*out = new(string)
		**out = **in
	}
	if in.EnterpriseManagedConfig != nil {
		in, out := &in.EnterpriseManagedConfig, &out.EnterpriseManagedConfig
		*out = new(EnterpriseManagedConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.InstallationCommand != nil {
		in, out := &in.InstallationCommand, &out.InstallationCommand
		*out = new(string)
		**out = **in
	}
	if in.Instructions != nil {
		in, out := &in.Instructions, &out.Instructions
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]LabelsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LocalConfig != nil {
		in, out := &in.LocalConfig, &out.LocalConfig
		*out = new(LocalConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalConfigSecretID != nil {
		in, out := &in.LocalConfigSecretID, &out.LocalConfigSecretID
		*out = new(string)
		**out = **in
	}
	if in.LocalConfigVaultKey != nil {
		in, out := &in.LocalConfigVaultKey, &out.LocalConfigVaultKey
		*out = new(string)
		**out = **in
	}
	if in.LocalConfigVaultPath != nil {
		in, out := &in.LocalConfigVaultPath, &out.LocalConfigVaultPath
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OauthClientSecretVaultKey != nil {
		in, out := &in.OauthClientSecretVaultKey, &out.OauthClientSecretVaultKey
		*out = new(string)
		**out = **in
	}
	if in.OauthClientSecretVaultPath != nil {
		in, out := &in.OauthClientSecretVaultPath, &out.OauthClientSecretVaultPath
		*out = new(string)
		**out = **in
	}
	if in.RemoteConfig != nil {
		in, out := &in.RemoteConfig, &out.RemoteConfig
		*out = new(RemoteConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.RequiresAuth != nil {
		in, out := &in.RequiresAuth, &out.RequiresAuth
		*out = new(bool)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserConfig != nil {
		in, out := &in.UserConfig, &out.UserConfig
		*out = make(map[string]UserConfigParameters, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCatalogItemParameters.
func (in *RegistryCatalogItemParameters) DeepCopy() *RegistryCatalogItemParameters {
	if in == nil {
		return nil
	}
	out := new(RegistryCatalogItemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCatalogItemSpec) DeepCopyInto(out *RegistryCatalogItemSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCatalogItemSpec.
func (in *RegistryCatalogItemSpec) DeepCopy() *RegistryCatalogItemSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryCatalogItemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryCatalogItemStatus) DeepCopyInto(out *RegistryCatalogItemStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryCatalogItemStatus.
func (in *RegistryCatalogItemStatus) DeepCopy() *RegistryCatalogItemStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryCatalogItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteConfigInitParameters) DeepCopyInto(out *RemoteConfigInitParameters) {
	*out = *in
	if in.OauthConfig != nil {
		in, out := &in.OauthConfig, &out.OauthConfig
		*out = new(OauthConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteConfigInitParameters.
func (in *RemoteConfigInitParameters) DeepCopy() *RemoteConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(RemoteConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteConfigObservation) DeepCopyInto(out *RemoteConfigObservation) {
	*out = *in
	if in.OauthConfig != nil {
		in, out := &in.OauthConfig, &out.OauthConfig
		*out = new(OauthConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteConfigObservation.
func (in *RemoteConfigObservation) DeepCopy() *RemoteConfigObservation {
	if in == nil {
		return nil
	}
	out := new(RemoteConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteConfigParameters) DeepCopyInto(out *RemoteConfigParameters) {
	*out = *in
	if in.OauthConfig != nil {
		in, out := &in.OauthConfig, &out.OauthConfig
		*out = new(OauthConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteConfigParameters.
func (in *RemoteConfigParameters) DeepCopy() *RemoteConfigParameters {
	if in == nil {
		return nil
	}
	out := new(RemoteConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInstallation) DeepCopyInto(out *ServerInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInstallation.
func (in *ServerInstallation) DeepCopy() *ServerInstallation {
	if in == nil {
		return nil
	}
	out := new(ServerInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInstallationInitParameters) DeepCopyInto(out *ServerInstallationInitParameters) {
	*out = *in
	if in.AccessTokenSecretRef != nil {
		in, out := &in.AccessTokenSecretRef, &out.AccessTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AgentIds != nil {
		in, out := &in.AgentIds, &out.AgentIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CatalogID != nil {
		in, out := &in.CatalogID, &out.CatalogID
		*out = new(string)
		**out = **in
	}
	if in.CatalogIDRef != nil {
		in, out := &in.CatalogIDRef, &out.CatalogIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CatalogIDSelector != nil {
		in, out := &in.CatalogIDSelector, &out.CatalogIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvironmentValues != nil {
		in, out := &in.EnvironmentValues, &out.EnvironmentValues
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsByosVault != nil {
		in, out := &in.IsByosVault, &out.IsByosVault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.UserConfigValues != nil {
		in, out := &in.UserConfigValues, &out.UserConfigValues
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInstallationInitParameters.
func (in *ServerInstallationInitParameters) DeepCopy() *ServerInstallationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServerInstallationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInstallationList) DeepCopyInto(out *ServerInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInstallationList.
func (in *ServerInstallationList) DeepCopy() *ServerInstallationList {
	if in == nil {
		return nil
	}
	out := new(ServerInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInstallationObservation) DeepCopyInto(out *ServerInstallationObservation) {
	*out = *in
	if in.AgentIds != nil {
		in, out := &in.AgentIds, &out.AgentIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CatalogID != nil {
		in, out := &in.CatalogID, &out.CatalogID
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentValues != nil {
		in, out := &in.EnvironmentValues, &out.EnvironmentValues
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsByosVault != nil {
		in, out := &in.IsByosVault, &out.IsByosVault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.ToolIDByName != nil {
		in, out := &in.ToolIDByName, &out.ToolIDByName
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserConfigValues != nil {
		in, out := &in.UserConfigValues, &out.UserConfigValues
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInstallationObservation.
func (in *ServerInstallationObservation) DeepCopy() *ServerInstallationObservation {
	if in == nil {
		return nil
	}
	out := new(ServerInstallationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInstallationParameters) DeepCopyInto(out *ServerInstallationParameters) {
	*out = *in
	if in.AccessTokenSecretRef != nil {
		in, out := &in.AccessTokenSecretRef, &out.AccessTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AgentIds != nil {
		in, out := &in.AgentIds, &out.AgentIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CatalogID != nil {
		in, out := &in.CatalogID, &out.CatalogID
		*out = new(string)
		**out = **in
	}
	if in.CatalogIDRef != nil {
		in, out := &in.CatalogIDRef, &out.CatalogIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CatalogIDSelector != nil {
		in, out := &in.CatalogIDSelector, &out.CatalogIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvironmentValues != nil {
		in, out := &in.EnvironmentValues, &out.EnvironmentValues
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsByosVault != nil {
		in, out := &in.IsByosVault, &out.IsByosVault
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SecretID != nil {
		in, out := &in.SecretID, &out.SecretID
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.TeamID != nil {
		in, out := &in.TeamID, &out.TeamID
		*out = new(string)
		**out = **in
	}
	if in.UserConfigValues != nil {
		in, out := &in.UserConfigValues, &out.UserConfigValues
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInstallationParameters.
func (in *ServerInstallationParameters) DeepCopy() *ServerInstallationParameters {
	if in == nil {
		return nil
	}
	out := new(ServerInstallationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInstallationSpec) DeepCopyInto(out *ServerInstallationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInstallationSpec.
func (in *ServerInstallationSpec) DeepCopy() *ServerInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(ServerInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerInstallationStatus) DeepCopyInto(out *ServerInstallationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerInstallationStatus.
func (in *ServerInstallationStatus) DeepCopy() *ServerInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(ServerInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsInitParameters) DeepCopyInto(out *ToolsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsInitParameters.
func (in *ToolsInitParameters) DeepCopy() *ToolsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ToolsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsObservation) DeepCopyInto(out *ToolsObservation) {
	*out = *in
	if in.AssignedAgentCount != nil {
		in, out := &in.AssignedAgentCount, &out.AssignedAgentCount
		*out = new(float64)
		**out = **in
	}
	if in.AssignedAgents != nil {
		in, out := &in.AssignedAgents, &out.AssignedAgents
		*out = make([]AssignedAgentsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsObservation.
func (in *ToolsObservation) DeepCopy() *ToolsObservation {
	if in == nil {
		return nil
	}
	out := new(ToolsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsParameters) DeepCopyInto(out *ToolsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsParameters.
func (in *ToolsParameters) DeepCopy() *ToolsParameters {
	if in == nil {
		return nil
	}
	out := new(ToolsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserConfigInitParameters) DeepCopyInto(out *UserConfigInitParameters) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Multiple != nil {
		in, out := &in.Multiple, &out.Multiple
		*out = new(bool)
		**out = **in
	}
	if in.PromptOnInstallation != nil {
		in, out := &in.PromptOnInstallation, &out.PromptOnInstallation
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Sensitive != nil {
		in, out := &in.Sensitive, &out.Sensitive
		*out = new(bool)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserConfigInitParameters.
func (in *UserConfigInitParameters) DeepCopy() *UserConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserConfigObservation) DeepCopyInto(out *UserConfigObservation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Multiple != nil {
		in, out := &in.Multiple, &out.Multiple
		*out = new(bool)
		**out = **in
	}
	if in.PromptOnInstallation != nil {
		in, out := &in.PromptOnInstallation, &out.PromptOnInstallation
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Sensitive != nil {
		in, out := &in.Sensitive, &out.Sensitive
		*out = new(bool)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserConfigObservation.
func (in *UserConfigObservation) DeepCopy() *UserConfigObservation {
	if in == nil {
		return nil
	}
	out := new(UserConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserConfigParameters) DeepCopyInto(out *UserConfigParameters) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Multiple != nil {
		in, out := &in.Multiple, &out.Multiple
		*out = new(bool)
		**out = **in
	}
	if in.PromptOnInstallation != nil {
		in, out := &in.PromptOnInstallation, &out.PromptOnInstallation
		*out = new(bool)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Sensitive != nil {
		in, out := &in.Sensitive, &out.Sensitive
		*out = new(bool)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserConfigParameters.
func (in *UserConfigParameters) DeepCopy() *UserConfigParameters {
	if in == nil {
		return nil
	}
	out := new(UserConfigParameters)
	in.DeepCopyInto(out)
	return out
}
