//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentInitParameters) DeepCopyInto(out *AgentInitParameters) {
	*out = *in
	if in.BuiltInAgentConfig != nil {
		in, out := &in.BuiltInAgentConfig, &out.BuiltInAgentConfig
		*out = make([]BuiltInAgentConfigInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectorIds != nil {
		in, out := &in.ConnectorIds, &out.ConnectorIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ConsiderContextUntrusted != nil {
		in, out := &in.ConsiderContextUntrusted, &out.ConsiderContextUntrusted
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.IncomingEmailAllowedDomain != nil {
		in, out := &in.IncomingEmailAllowedDomain, &out.IncomingEmailAllowedDomain
		*out = new(string)
		**out = **in
	}
	if in.IncomingEmailEnabled != nil {
		in, out := &in.IncomingEmailEnabled, &out.IncomingEmailEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncomingEmailSecurityMode != nil {
		in, out := &in.IncomingEmailSecurityMode, &out.IncomingEmailSecurityMode
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.KnowledgeBaseIds != nil {
		in, out := &in.KnowledgeBaseIds, &out.KnowledgeBaseIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]LabelsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LlmAPIKeyID != nil {
		in, out := &in.LlmAPIKeyID, &out.LlmAPIKeyID
		*out = new(string)
		**out = **in
	}
	if in.LlmModel != nil {
		in, out := &in.LlmModel, &out.LlmModel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.SuggestedPrompts != nil {
		in, out := &in.SuggestedPrompts, &out.SuggestedPrompts
		*out = make([]SuggestedPromptsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(string)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentInitParameters.
func (in *AgentInitParameters) DeepCopy() *AgentInitParameters {
	if in == nil {
		return nil
	}
	out := new(AgentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentObservation) DeepCopyInto(out *AgentObservation) {
	*out = *in
	if in.BuiltInAgentConfig != nil {
		in, out := &in.BuiltInAgentConfig, &out.BuiltInAgentConfig
		*out = make([]BuiltInAgentConfigObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectorIds != nil {
		in, out := &in.ConnectorIds, &out.ConnectorIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ConsiderContextUntrusted != nil {
		in, out := &in.ConsiderContextUntrusted, &out.ConsiderContextUntrusted
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.IncomingEmailAllowedDomain != nil {
		in, out := &in.IncomingEmailAllowedDomain, &out.IncomingEmailAllowedDomain
		*out = new(string)
		**out = **in
	}
	if in.IncomingEmailEnabled != nil {
		in, out := &in.IncomingEmailEnabled, &out.IncomingEmailEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncomingEmailSecurityMode != nil {
		in, out := &in.IncomingEmailSecurityMode, &out.IncomingEmailSecurityMode
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.KnowledgeBaseIds != nil {
		in, out := &in.KnowledgeBaseIds, &out.KnowledgeBaseIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]LabelsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LlmAPIKeyID != nil {
		in, out := &in.LlmAPIKeyID, &out.LlmAPIKeyID
		*out = new(string)
		**out = **in
	}
	if in.LlmModel != nil {
		in, out := &in.LlmModel, &out.LlmModel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.SuggestedPrompts != nil {
		in, out := &in.SuggestedPrompts, &out.SuggestedPrompts
		*out = make([]SuggestedPromptsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(string)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentObservation.
func (in *AgentObservation) DeepCopy() *AgentObservation {
	if in == nil {
		return nil
	}
	out := new(AgentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentParameters) DeepCopyInto(out *AgentParameters) {
	*out = *in
	if in.BuiltInAgentConfig != nil {
		in, out := &in.BuiltInAgentConfig, &out.BuiltInAgentConfig
		*out = make([]BuiltInAgentConfigParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectorIds != nil {
		in, out := &in.ConnectorIds, &out.ConnectorIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ConsiderContextUntrusted != nil {
		in, out := &in.ConsiderContextUntrusted, &out.ConsiderContextUntrusted
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.IncomingEmailAllowedDomain != nil {
		in, out := &in.IncomingEmailAllowedDomain, &out.IncomingEmailAllowedDomain
		*out = new(string)
		**out = **in
	}
	if in.IncomingEmailEnabled != nil {
		in, out := &in.IncomingEmailEnabled, &out.IncomingEmailEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IncomingEmailSecurityMode != nil {
		in, out := &in.IncomingEmailSecurityMode, &out.IncomingEmailSecurityMode
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.KnowledgeBaseIds != nil {
		in, out := &in.KnowledgeBaseIds, &out.KnowledgeBaseIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]LabelsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LlmAPIKeyID != nil {
		in, out := &in.LlmAPIKeyID, &out.LlmAPIKeyID
		*out = new(string)
		**out = **in
	}
	if in.LlmModel != nil {
		in, out := &in.LlmModel, &out.LlmModel
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.SuggestedPrompts != nil {
		in, out := &in.SuggestedPrompts, &out.SuggestedPrompts
		*out = make([]SuggestedPromptsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(string)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentParameters.
func (in *AgentParameters) DeepCopy() *AgentParameters {
	if in == nil {
		return nil
	}
	out := new(AgentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuiltInAgentConfigInitParameters) DeepCopyInto(out *BuiltInAgentConfigInitParameters) {
	*out = *in
	if in.AutoConfigureOnToolDiscovery != nil {
		in, out := &in.AutoConfigureOnToolDiscovery, &out.AutoConfigureOnToolDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.MaxRounds != nil {
		in, out := &in.MaxRounds, &out.MaxRounds
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuiltInAgentConfigInitParameters.
func (in *BuiltInAgentConfigInitParameters) DeepCopy() *BuiltInAgentConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(BuiltInAgentConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuiltInAgentConfigObservation) DeepCopyInto(out *BuiltInAgentConfigObservation) {
	*out = *in
	if in.AutoConfigureOnToolDiscovery != nil {
		in, out := &in.AutoConfigureOnToolDiscovery, &out.AutoConfigureOnToolDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.MaxRounds != nil {
		in, out := &in.MaxRounds, &out.MaxRounds
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuiltInAgentConfigObservation.
func (in *BuiltInAgentConfigObservation) DeepCopy() *BuiltInAgentConfigObservation {
	if in == nil {
		return nil
	}
	out := new(BuiltInAgentConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuiltInAgentConfigParameters) DeepCopyInto(out *BuiltInAgentConfigParameters) {
	*out = *in
	if in.AutoConfigureOnToolDiscovery != nil {
		in, out := &in.AutoConfigureOnToolDiscovery, &out.AutoConfigureOnToolDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.MaxRounds != nil {
		in, out := &in.MaxRounds, &out.MaxRounds
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuiltInAgentConfigParameters.
func (in *BuiltInAgentConfigParameters) DeepCopy() *BuiltInAgentConfigParameters {
	if in == nil {
		return nil
	}
	out := new(BuiltInAgentConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelsInitParameters) DeepCopyInto(out *LabelsInitParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelsInitParameters.
func (in *LabelsInitParameters) DeepCopy() *LabelsInitParameters {
	if in == nil {
		return nil
	}
	out := new(LabelsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelsObservation) DeepCopyInto(out *LabelsObservation) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelsObservation.
func (in *LabelsObservation) DeepCopy() *LabelsObservation {
	if in == nil {
		return nil
	}
	out := new(LabelsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelsParameters) DeepCopyInto(out *LabelsParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelsParameters.
func (in *LabelsParameters) DeepCopy() *LabelsParameters {
	if in == nil {
		return nil
	}
	out := new(LabelsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedPromptsInitParameters) DeepCopyInto(out *SuggestedPromptsInitParameters) {
	*out = *in
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(string)
		**out = **in
	}
	if in.SummaryTitle != nil {
		in, out := &in.SummaryTitle, &out.SummaryTitle
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedPromptsInitParameters.
func (in *SuggestedPromptsInitParameters) DeepCopy() *SuggestedPromptsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SuggestedPromptsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedPromptsObservation) DeepCopyInto(out *SuggestedPromptsObservation) {
	*out = *in
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(string)
		**out = **in
	}
	if in.SummaryTitle != nil {
		in, out := &in.SummaryTitle, &out.SummaryTitle
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedPromptsObservation.
func (in *SuggestedPromptsObservation) DeepCopy() *SuggestedPromptsObservation {
	if in == nil {
		return nil
	}
	out := new(SuggestedPromptsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuggestedPromptsParameters) DeepCopyInto(out *SuggestedPromptsParameters) {
	*out = *in
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(string)
		**out = **in
	}
	if in.SummaryTitle != nil {
		in, out := &in.SummaryTitle, &out.SummaryTitle
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuggestedPromptsParameters.
func (in *SuggestedPromptsParameters) DeepCopy() *SuggestedPromptsParameters {
	if in == nil {
		return nil
	}
	out := new(SuggestedPromptsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBatch) DeepCopyInto(out *ToolBatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBatch.
func (in *ToolBatch) DeepCopy() *ToolBatch {
	if in == nil {
		return nil
	}
	out := new(ToolBatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolBatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBatchInitParameters) DeepCopyInto(out *ToolBatchInitParameters) {
	*out = *in
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentIDRef != nil {
		in, out := &in.AgentIDRef, &out.AgentIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentIDSelector != nil {
		in, out := &in.AgentIDSelector, &out.AgentIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialResolutionMode != nil {
		in, out := &in.CredentialResolutionMode, &out.CredentialResolutionMode
		*out = new(string)
		**out = **in
	}
	if in.McpServerID != nil {
		in, out := &in.McpServerID, &out.McpServerID
		*out = new(string)
		**out = **in
	}
	if in.McpServerIDRef != nil {
		in, out := &in.McpServerIDRef, &out.McpServerIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.McpServerIDSelector != nil {
		in, out := &in.McpServerIDSelector, &out.McpServerIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolIds != nil {
		in, out := &in.ToolIds, &out.ToolIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBatchInitParameters.
func (in *ToolBatchInitParameters) DeepCopy() *ToolBatchInitParameters {
	if in == nil {
		return nil
	}
	out := new(ToolBatchInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBatchList) DeepCopyInto(out *ToolBatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToolBatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBatchList.
func (in *ToolBatchList) DeepCopy() *ToolBatchList {
	if in == nil {
		return nil
	}
	out := new(ToolBatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolBatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBatchObservation) DeepCopyInto(out *ToolBatchObservation) {
	*out = *in
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.CredentialResolutionMode != nil {
		in, out := &in.CredentialResolutionMode, &out.CredentialResolutionMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.McpServerID != nil {
		in, out := &in.McpServerID, &out.McpServerID
		*out = new(string)
		**out = **in
	}
	if in.ToolIds != nil {
		in, out := &in.ToolIds, &out.ToolIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBatchObservation.
func (in *ToolBatchObservation) DeepCopy() *ToolBatchObservation {
	if in == nil {
		return nil
	}
	out := new(ToolBatchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBatchParameters) DeepCopyInto(out *ToolBatchParameters) {
	*out = *in
	if in.AgentID != nil {
		in, out := &in.AgentID, &out.AgentID
		*out = new(string)
		**out = **in
	}
	if in.AgentIDRef != nil {
		in, out := &in.AgentIDRef, &out.AgentIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentIDSelector != nil {
		in, out := &in.AgentIDSelector, &out.AgentIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialResolutionMode != nil {
		in, out := &in.CredentialResolutionMode, &out.CredentialResolutionMode
		*out = new(string)
		**out = **in
	}
	if in.McpServerID != nil {
		in, out := &in.McpServerID, &out.McpServerID
		*out = new(string)
		**out = **in
	}
	if in.McpServerIDRef != nil {
		in, out := &in.McpServerIDRef, &out.McpServerIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.McpServerIDSelector != nil {
		in, out := &in.McpServerIDSelector, &out.McpServerIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolIds != nil {
		in, out := &in.ToolIds, &out.ToolIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBatchParameters.
func (in *ToolBatchParameters) DeepCopy() *ToolBatchParameters {
	if in == nil {
		return nil
	}
	out := new(ToolBatchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBatchSpec) DeepCopyInto(out *ToolBatchSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBatchSpec.
func (in *ToolBatchSpec) DeepCopy() *ToolBatchSpec {
	if in == nil {
		return nil
	}
	out := new(ToolBatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolBatchStatus) DeepCopyInto(out *ToolBatchStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolBatchStatus.
func (in *ToolBatchStatus) DeepCopy() *ToolBatchStatus {
	if in == nil {
		return nil
	}
	out := new(ToolBatchStatus)
	in.DeepCopyInto(out)
	return out
}
