// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ToolBatchInitParameters struct {

	// Agent UUID. Pass the `id` from `archestra_agent` / `archestra_llm_proxy` / `archestra_mcp_gateway`.
	// +crossplane:generate:reference:type=github.com/archestra-ai/provider-archestra/apis/cluster/agent/v1alpha1.Agent
	AgentID *string `json:"agentId,omitempty" tf:"agent_id,omitempty"`

	// Reference to a Agent in agent to populate agentId.
	// +kubebuilder:validation:Optional
	AgentIDRef *v1.Reference `json:"agentIdRef,omitempty" tf:"-"`

	// Selector for a Agent in agent to populate agentId.
	// +kubebuilder:validation:Optional
	AgentIDSelector *v1.Selector `json:"agentIdSelector,omitempty" tf:"-"`

	// How the agent resolves credentials when calling tools in this batch. Same semantics as `archestra_agent_tool.credential_resolution_mode`. Defaults to `static`.
	//
	// ~> **Asymmetric replacement.** Changing this value forces the resource to be replaced (drops every assignment and recreates), because the credential mode is per-assignment metadata that the bulk endpoint can't patch in place. Adding/removing entries in `tool_ids` is patched in-place — only this attribute, `agent_id`, and `mcp_server_id` trigger replacement.
	CredentialResolutionMode *string `json:"credentialResolutionMode,omitempty" tf:"credential_resolution_mode,omitempty"`

	// MCP server installation UUID. Pass `archestra_mcp_server_installation.<n>.id`.
	// +crossplane:generate:reference:type=github.com/archestra-ai/provider-archestra/apis/cluster/mcp/v1alpha1.ServerInstallation
	McpServerID *string `json:"mcpServerId,omitempty" tf:"mcp_server_id,omitempty"`

	// Reference to a ServerInstallation in mcp to populate mcpServerId.
	// +kubebuilder:validation:Optional
	McpServerIDRef *v1.Reference `json:"mcpServerIdRef,omitempty" tf:"-"`

	// Selector for a ServerInstallation in mcp to populate mcpServerId.
	// +kubebuilder:validation:Optional
	McpServerIDSelector *v1.Selector `json:"mcpServerIdSelector,omitempty" tf:"-"`

	// Set of bare tool UUIDs to assign. Typically `[for t in archestra_mcp_server_installation.<n>.tools : t.id]`. Adding members triggers a bulk-assign on the new ones only; removing members unassigns each individually. **Patched in-place — does not force replacement.**
	// +listType=set
	ToolIds []*string `json:"toolIds,omitempty" tf:"tool_ids,omitempty"`
}

type ToolBatchObservation struct {

	// Agent UUID. Pass the `id` from `archestra_agent` / `archestra_llm_proxy` / `archestra_mcp_gateway`.
	AgentID *string `json:"agentId,omitempty" tf:"agent_id,omitempty"`

	// How the agent resolves credentials when calling tools in this batch. Same semantics as `archestra_agent_tool.credential_resolution_mode`. Defaults to `static`.
	//
	// ~> **Asymmetric replacement.** Changing this value forces the resource to be replaced (drops every assignment and recreates), because the credential mode is per-assignment metadata that the bulk endpoint can't patch in place. Adding/removing entries in `tool_ids` is patched in-place — only this attribute, `agent_id`, and `mcp_server_id` trigger replacement.
	CredentialResolutionMode *string `json:"credentialResolutionMode,omitempty" tf:"credential_resolution_mode,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// MCP server installation UUID. Pass `archestra_mcp_server_installation.<n>.id`.
	McpServerID *string `json:"mcpServerId,omitempty" tf:"mcp_server_id,omitempty"`

	// Set of bare tool UUIDs to assign. Typically `[for t in archestra_mcp_server_installation.<n>.tools : t.id]`. Adding members triggers a bulk-assign on the new ones only; removing members unassigns each individually. **Patched in-place — does not force replacement.**
	// +listType=set
	ToolIds []*string `json:"toolIds,omitempty" tf:"tool_ids,omitempty"`
}

type ToolBatchParameters struct {

	// Agent UUID. Pass the `id` from `archestra_agent` / `archestra_llm_proxy` / `archestra_mcp_gateway`.
	// +crossplane:generate:reference:type=github.com/archestra-ai/provider-archestra/apis/cluster/agent/v1alpha1.Agent
	// +kubebuilder:validation:Optional
	AgentID *string `json:"agentId,omitempty" tf:"agent_id,omitempty"`

	// Reference to a Agent in agent to populate agentId.
	// +kubebuilder:validation:Optional
	AgentIDRef *v1.Reference `json:"agentIdRef,omitempty" tf:"-"`

	// Selector for a Agent in agent to populate agentId.
	// +kubebuilder:validation:Optional
	AgentIDSelector *v1.Selector `json:"agentIdSelector,omitempty" tf:"-"`

	// How the agent resolves credentials when calling tools in this batch. Same semantics as `archestra_agent_tool.credential_resolution_mode`. Defaults to `static`.
	//
	// ~> **Asymmetric replacement.** Changing this value forces the resource to be replaced (drops every assignment and recreates), because the credential mode is per-assignment metadata that the bulk endpoint can't patch in place. Adding/removing entries in `tool_ids` is patched in-place — only this attribute, `agent_id`, and `mcp_server_id` trigger replacement.
	// +kubebuilder:validation:Optional
	CredentialResolutionMode *string `json:"credentialResolutionMode,omitempty" tf:"credential_resolution_mode,omitempty"`

	// MCP server installation UUID. Pass `archestra_mcp_server_installation.<n>.id`.
	// +crossplane:generate:reference:type=github.com/archestra-ai/provider-archestra/apis/cluster/mcp/v1alpha1.ServerInstallation
	// +kubebuilder:validation:Optional
	McpServerID *string `json:"mcpServerId,omitempty" tf:"mcp_server_id,omitempty"`

	// Reference to a ServerInstallation in mcp to populate mcpServerId.
	// +kubebuilder:validation:Optional
	McpServerIDRef *v1.Reference `json:"mcpServerIdRef,omitempty" tf:"-"`

	// Selector for a ServerInstallation in mcp to populate mcpServerId.
	// +kubebuilder:validation:Optional
	McpServerIDSelector *v1.Selector `json:"mcpServerIdSelector,omitempty" tf:"-"`

	// Set of bare tool UUIDs to assign. Typically `[for t in archestra_mcp_server_installation.<n>.tools : t.id]`. Adding members triggers a bulk-assign on the new ones only; removing members unassigns each individually. **Patched in-place — does not force replacement.**
	// +kubebuilder:validation:Optional
	// +listType=set
	ToolIds []*string `json:"toolIds,omitempty" tf:"tool_ids,omitempty"`
}

// ToolBatchSpec defines the desired state of ToolBatch
type ToolBatchSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ToolBatchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolBatchInitParameters `json:"initProvider,omitempty"`
}

// ToolBatchStatus defines the observed state of ToolBatch.
type ToolBatchStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolBatchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolBatch is the Schema for the ToolBatchs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,archestra}
type ToolBatch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.toolIds) || (has(self.initProvider) && has(self.initProvider.toolIds))",message="spec.forProvider.toolIds is a required parameter"
	Spec   ToolBatchSpec   `json:"spec"`
	Status ToolBatchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolBatchList contains a list of ToolBatchs
type ToolBatchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolBatch `json:"items"`
}

// Repository type metadata.
var (
	ToolBatch_Kind             = "ToolBatch"
	ToolBatch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolBatch_Kind}.String()
	ToolBatch_KindAPIVersion   = ToolBatch_Kind + "." + CRDGroupVersion.String()
	ToolBatch_GroupVersionKind = CRDGroupVersion.WithKind(ToolBatch_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolBatch{}, &ToolBatchList{})
}
