// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AuthFieldsInitParameters struct {

	// Description of the field
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display label for the field
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// Field name (used as environment variable)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this field is required
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Field type: 'text', 'password', 'select', etc.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AuthFieldsObservation struct {

	// Description of the field
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display label for the field
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// Field name (used as environment variable)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this field is required
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Field type: 'text', 'password', 'select', etc.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AuthFieldsParameters struct {

	// Description of the field
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display label for the field
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// Field name (used as environment variable)
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Whether this field is required
	// +kubebuilder:validation:Optional
	Required *bool `json:"required" tf:"required,omitempty"`

	// Field type: 'text', 'password', 'select', etc.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type EnterpriseManagedConfigInitParameters struct {

	// Assertion exchange mode. One of `exchange`, `passthrough`.
	AssertionMode *string `json:"assertionMode,omitempty" tf:"assertion_mode,omitempty"`

	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	BodyFieldName *string `json:"bodyFieldName,omitempty" tf:"body_field_name,omitempty"`

	// Cache TTL in seconds. Non-negative.
	CacheTTLSeconds *float64 `json:"cacheTtlSeconds,omitempty" tf:"cache_ttl_seconds,omitempty"`

	ClientIDOverride *string `json:"clientIdOverride,omitempty" tf:"client_id_override,omitempty"`

	EnvVarName *string `json:"envVarName,omitempty" tf:"env_var_name,omitempty"`

	// Behavior when credential exchange fails. One of `fail_closed`, `fallback_to_dynamic`, `fallback_to_static`.
	FallbackMode *string `json:"fallbackMode,omitempty" tf:"fallback_mode,omitempty"`

	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Identity provider UUID issuing credentials.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// Credential type requested. One of `id_jag`, `bearer_token`, `secret`, `service_account`, `opaque_json`.
	RequestedCredentialType *string `json:"requestedCredentialType,omitempty" tf:"requested_credential_type,omitempty"`

	RequestedIssuer *string `json:"requestedIssuer,omitempty" tf:"requested_issuer,omitempty"`

	ResourceIdentifier *string `json:"resourceIdentifier,omitempty" tf:"resource_identifier,omitempty"`

	// Resource type. One of `mcp`, `oauth_protected_resource`, `secret`, `service_account`, `custom_http`.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	ResponseFieldPath *string `json:"responseFieldPath,omitempty" tf:"response_field_path,omitempty"`

	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// How the token is injected into the downstream request. One of `authorization_bearer`, `raw_authorization`, `header`, `env`, `body_field`.
	TokenInjectionMode *string `json:"tokenInjectionMode,omitempty" tf:"token_injection_mode,omitempty"`
}

type EnterpriseManagedConfigObservation struct {

	// Assertion exchange mode. One of `exchange`, `passthrough`.
	AssertionMode *string `json:"assertionMode,omitempty" tf:"assertion_mode,omitempty"`

	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	BodyFieldName *string `json:"bodyFieldName,omitempty" tf:"body_field_name,omitempty"`

	// Cache TTL in seconds. Non-negative.
	CacheTTLSeconds *float64 `json:"cacheTtlSeconds,omitempty" tf:"cache_ttl_seconds,omitempty"`

	ClientIDOverride *string `json:"clientIdOverride,omitempty" tf:"client_id_override,omitempty"`

	EnvVarName *string `json:"envVarName,omitempty" tf:"env_var_name,omitempty"`

	// Behavior when credential exchange fails. One of `fail_closed`, `fallback_to_dynamic`, `fallback_to_static`.
	FallbackMode *string `json:"fallbackMode,omitempty" tf:"fallback_mode,omitempty"`

	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Identity provider UUID issuing credentials.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// Credential type requested. One of `id_jag`, `bearer_token`, `secret`, `service_account`, `opaque_json`.
	RequestedCredentialType *string `json:"requestedCredentialType,omitempty" tf:"requested_credential_type,omitempty"`

	RequestedIssuer *string `json:"requestedIssuer,omitempty" tf:"requested_issuer,omitempty"`

	ResourceIdentifier *string `json:"resourceIdentifier,omitempty" tf:"resource_identifier,omitempty"`

	// Resource type. One of `mcp`, `oauth_protected_resource`, `secret`, `service_account`, `custom_http`.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	ResponseFieldPath *string `json:"responseFieldPath,omitempty" tf:"response_field_path,omitempty"`

	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// How the token is injected into the downstream request. One of `authorization_bearer`, `raw_authorization`, `header`, `env`, `body_field`.
	TokenInjectionMode *string `json:"tokenInjectionMode,omitempty" tf:"token_injection_mode,omitempty"`
}

type EnterpriseManagedConfigParameters struct {

	// Assertion exchange mode. One of `exchange`, `passthrough`.
	// +kubebuilder:validation:Optional
	AssertionMode *string `json:"assertionMode,omitempty" tf:"assertion_mode,omitempty"`

	// +kubebuilder:validation:Optional
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// +kubebuilder:validation:Optional
	BodyFieldName *string `json:"bodyFieldName,omitempty" tf:"body_field_name,omitempty"`

	// Cache TTL in seconds. Non-negative.
	// +kubebuilder:validation:Optional
	CacheTTLSeconds *float64 `json:"cacheTtlSeconds,omitempty" tf:"cache_ttl_seconds,omitempty"`

	// +kubebuilder:validation:Optional
	ClientIDOverride *string `json:"clientIdOverride,omitempty" tf:"client_id_override,omitempty"`

	// +kubebuilder:validation:Optional
	EnvVarName *string `json:"envVarName,omitempty" tf:"env_var_name,omitempty"`

	// Behavior when credential exchange fails. One of `fail_closed`, `fallback_to_dynamic`, `fallback_to_static`.
	// +kubebuilder:validation:Optional
	FallbackMode *string `json:"fallbackMode,omitempty" tf:"fallback_mode,omitempty"`

	// +kubebuilder:validation:Optional
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Identity provider UUID issuing credentials.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// Credential type requested. One of `id_jag`, `bearer_token`, `secret`, `service_account`, `opaque_json`.
	// +kubebuilder:validation:Optional
	RequestedCredentialType *string `json:"requestedCredentialType,omitempty" tf:"requested_credential_type,omitempty"`

	// +kubebuilder:validation:Optional
	RequestedIssuer *string `json:"requestedIssuer,omitempty" tf:"requested_issuer,omitempty"`

	// +kubebuilder:validation:Optional
	ResourceIdentifier *string `json:"resourceIdentifier,omitempty" tf:"resource_identifier,omitempty"`

	// Resource type. One of `mcp`, `oauth_protected_resource`, `secret`, `service_account`, `custom_http`.
	// +kubebuilder:validation:Optional
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// +kubebuilder:validation:Optional
	ResponseFieldPath *string `json:"responseFieldPath,omitempty" tf:"response_field_path,omitempty"`

	// +kubebuilder:validation:Optional
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// How the token is injected into the downstream request. One of `authorization_bearer`, `raw_authorization`, `header`, `env`, `body_field`.
	// +kubebuilder:validation:Optional
	TokenInjectionMode *string `json:"tokenInjectionMode,omitempty" tf:"token_injection_mode,omitempty"`
}

type EnvFromInitParameters struct {

	// Name of the secret or configMap
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional prefix for environment variable names
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Source type: 'secret' or 'configMap'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EnvFromObservation struct {

	// Name of the secret or configMap
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Optional prefix for environment variable names
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Source type: 'secret' or 'configMap'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EnvFromParameters struct {

	// Name of the secret or configMap
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Optional prefix for environment variable names
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Source type: 'secret' or 'configMap'
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type EnvironmentInitParameters struct {

	// Default value. Use `jsonencode(...)` to encode non-string defaults (number, bool). Plain strings may be provided as-is.
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Human-readable description of the variable.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Environment variable name.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// When true, the value is mounted as a file at `/secrets/<key>` rather than injected as an env var.
	Mounted *bool `json:"mounted,omitempty" tf:"mounted,omitempty"`

	// Whether the installer must supply this value at install time. Required field on the wire — defaults to `false`.
	PromptOnInstallation *bool `json:"promptOnInstallation,omitempty" tf:"prompt_on_installation,omitempty"`

	// Whether the value must be set.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Variable type. One of `plain_text`, `secret`, `boolean`, `number`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value for `plain_text` / `secret` variables.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EnvironmentObservation struct {

	// Default value. Use `jsonencode(...)` to encode non-string defaults (number, bool). Plain strings may be provided as-is.
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Human-readable description of the variable.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Environment variable name.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// When true, the value is mounted as a file at `/secrets/<key>` rather than injected as an env var.
	Mounted *bool `json:"mounted,omitempty" tf:"mounted,omitempty"`

	// Whether the installer must supply this value at install time. Required field on the wire — defaults to `false`.
	PromptOnInstallation *bool `json:"promptOnInstallation,omitempty" tf:"prompt_on_installation,omitempty"`

	// Whether the value must be set.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Variable type. One of `plain_text`, `secret`, `boolean`, `number`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value for `plain_text` / `secret` variables.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EnvironmentParameters struct {

	// Default value. Use `jsonencode(...)` to encode non-string defaults (number, bool). Plain strings may be provided as-is.
	// +kubebuilder:validation:Optional
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Human-readable description of the variable.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Environment variable name.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// When true, the value is mounted as a file at `/secrets/<key>` rather than injected as an env var.
	// +kubebuilder:validation:Optional
	Mounted *bool `json:"mounted,omitempty" tf:"mounted,omitempty"`

	// Whether the installer must supply this value at install time. Required field on the wire — defaults to `false`.
	// +kubebuilder:validation:Optional
	PromptOnInstallation *bool `json:"promptOnInstallation,omitempty" tf:"prompt_on_installation,omitempty"`

	// Whether the value must be set.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Variable type. One of `plain_text`, `secret`, `boolean`, `number`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// Value for `plain_text` / `secret` variables.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ImagePullSecretsInitParameters struct {

	// Registry email (optional for `source = credentials`).
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Name of the existing Kubernetes secret (required for `source = existing`).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Registry password (required for `source = credentials`). Write-only: the backend never echoes it back. To stay consistent across refreshes the provider preserves it keyed by `(server, username)`; rotating either of those values drops the password from state and forces re-entry.
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Docker registry server URL (required for `source = credentials`).
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// Source of the pull secret. One of `existing`, `credentials`. Defaults to `existing` for backward compatibility when only `name` is set.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Registry username (required for `source = credentials`).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ImagePullSecretsObservation struct {

	// Registry email (optional for `source = credentials`).
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Name of the existing Kubernetes secret (required for `source = existing`).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Docker registry server URL (required for `source = credentials`).
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// Source of the pull secret. One of `existing`, `credentials`. Defaults to `existing` for backward compatibility when only `name` is set.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Registry username (required for `source = credentials`).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ImagePullSecretsParameters struct {

	// Registry email (optional for `source = credentials`).
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Name of the existing Kubernetes secret (required for `source = existing`).
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Registry password (required for `source = credentials`). Write-only: the backend never echoes it back. To stay consistent across refreshes the provider preserves it keyed by `(server, username)`; rotating either of those values drops the password from state and forces re-entry.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Docker registry server URL (required for `source = credentials`).
	// +kubebuilder:validation:Optional
	Server *string `json:"server,omitempty" tf:"server,omitempty"`

	// Source of the pull secret. One of `existing`, `credentials`. Defaults to `existing` for backward compatibility when only `name` is set.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Registry username (required for `source = credentials`).
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type LabelsInitParameters struct {

	// Label key
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Label value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LabelsObservation struct {

	// Label key
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Label value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LabelsParameters struct {

	// Label key
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// Label value
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type LocalConfigInitParameters struct {

	// Arguments to pass to the command
	Arguments []*string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// The executable command to run (e.g., 'node', 'python', 'npx'). Optional if Docker Image is set (will use image's default CMD).
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Custom Docker image URL. If not specified, Archestra's default base image will be used.
	DockerImage *string `json:"dockerImage,omitempty" tf:"docker_image,omitempty"`

	EnvFrom []EnvFromInitParameters `json:"envFrom,omitempty" tf:"env_from,omitempty"`

	Environment []EnvironmentInitParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// HTTP path for streamable-http transport (e.g., '/sse')
	HTTPPath *string `json:"httpPath,omitempty" tf:"http_path,omitempty"`

	// HTTP port for streamable-http transport. Range 0..65535.
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	ImagePullSecrets []ImagePullSecretsInitParameters `json:"imagePullSecrets,omitempty" tf:"image_pull_secrets,omitempty"`

	// Node port for the MCP server service. Kubernetes NodePort range 30000..32767.
	NodePort *float64 `json:"nodePort,omitempty" tf:"node_port,omitempty"`

	// Kubernetes service account for the MCP server pod
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Transport type: 'stdio' or 'streamable-http'. Defaults to 'stdio'
	TransportType *string `json:"transportType,omitempty" tf:"transport_type,omitempty"`
}

type LocalConfigObservation struct {

	// Arguments to pass to the command
	Arguments []*string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// The executable command to run (e.g., 'node', 'python', 'npx'). Optional if Docker Image is set (will use image's default CMD).
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Custom Docker image URL. If not specified, Archestra's default base image will be used.
	DockerImage *string `json:"dockerImage,omitempty" tf:"docker_image,omitempty"`

	EnvFrom []EnvFromObservation `json:"envFrom,omitempty" tf:"env_from,omitempty"`

	Environment []EnvironmentObservation `json:"environment,omitempty" tf:"environment,omitempty"`

	// HTTP path for streamable-http transport (e.g., '/sse')
	HTTPPath *string `json:"httpPath,omitempty" tf:"http_path,omitempty"`

	// HTTP port for streamable-http transport. Range 0..65535.
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	ImagePullSecrets []ImagePullSecretsObservation `json:"imagePullSecrets,omitempty" tf:"image_pull_secrets,omitempty"`

	// Node port for the MCP server service. Kubernetes NodePort range 30000..32767.
	NodePort *float64 `json:"nodePort,omitempty" tf:"node_port,omitempty"`

	// Kubernetes service account for the MCP server pod
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Transport type: 'stdio' or 'streamable-http'. Defaults to 'stdio'
	TransportType *string `json:"transportType,omitempty" tf:"transport_type,omitempty"`
}

type LocalConfigParameters struct {

	// Arguments to pass to the command
	// +kubebuilder:validation:Optional
	Arguments []*string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// The executable command to run (e.g., 'node', 'python', 'npx'). Optional if Docker Image is set (will use image's default CMD).
	// +kubebuilder:validation:Optional
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Custom Docker image URL. If not specified, Archestra's default base image will be used.
	// +kubebuilder:validation:Optional
	DockerImage *string `json:"dockerImage,omitempty" tf:"docker_image,omitempty"`

	// +kubebuilder:validation:Optional
	EnvFrom []EnvFromParameters `json:"envFrom,omitempty" tf:"env_from,omitempty"`

	// +kubebuilder:validation:Optional
	Environment []EnvironmentParameters `json:"environment,omitempty" tf:"environment,omitempty"`

	// HTTP path for streamable-http transport (e.g., '/sse')
	// +kubebuilder:validation:Optional
	HTTPPath *string `json:"httpPath,omitempty" tf:"http_path,omitempty"`

	// HTTP port for streamable-http transport. Range 0..65535.
	// +kubebuilder:validation:Optional
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	// +kubebuilder:validation:Optional
	ImagePullSecrets []ImagePullSecretsParameters `json:"imagePullSecrets,omitempty" tf:"image_pull_secrets,omitempty"`

	// Node port for the MCP server service. Kubernetes NodePort range 30000..32767.
	// +kubebuilder:validation:Optional
	NodePort *float64 `json:"nodePort,omitempty" tf:"node_port,omitempty"`

	// Kubernetes service account for the MCP server pod
	// +kubebuilder:validation:Optional
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Transport type: 'stdio' or 'streamable-http'. Defaults to 'stdio'
	// +kubebuilder:validation:Optional
	TransportType *string `json:"transportType,omitempty" tf:"transport_type,omitempty"`
}

type OauthConfigInitParameters struct {

	// Environment variable name to inject the acquired access token into.
	AccessTokenEnvVar *string `json:"accessTokenEnvVar,omitempty" tf:"access_token_env_var,omitempty"`

	// `aud` claim to request when performing token exchange.
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// Override for the OAuth authorization server root URL.
	AuthServerURL *string `json:"authServerUrl,omitempty" tf:"auth_server_url,omitempty"`

	// Custom OAuth authorization endpoint URL
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty" tf:"authorization_endpoint,omitempty"`

	// Prompt the installer through an interactive browser auth flow.
	BrowserAuth *bool `json:"browserAuth,omitempty" tf:"browser_auth,omitempty"`

	// OAuth Client ID. Leave empty if the server supports dynamic client registration.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// OAuth Client Secret (optional)
	ClientSecretSecretRef *v1.LocalSecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// Scopes requested by default when the server doesn't advertise its own.
	DefaultScopes []*string `json:"defaultScopes,omitempty" tf:"default_scopes,omitempty"`

	// Treat the server as a generic OAuth provider (skip vendor-specific probes).
	GenericOauth *bool `json:"genericOauth,omitempty" tf:"generic_oauth,omitempty"`

	// OAuth grant type. One of `authorization_code`, `client_credentials`.
	GrantType *string `json:"grantType,omitempty" tf:"grant_type,omitempty"`

	// Human-readable name of the OAuth provider for display.
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// Comma-separated list of redirect URIs
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// Route OAuth redirects through the Archestra proxy.
	RequiresProxy *bool `json:"requiresProxy,omitempty" tf:"requires_proxy,omitempty"`

	// URL of the protected-resource metadata document.
	ResourceMetadataURL *string `json:"resourceMetadataUrl,omitempty" tf:"resource_metadata_url,omitempty"`

	// List of OAuth scopes to request (e.g., ['read', 'write'])
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// Streamable-HTTP MCP server port override. Range 0..65535.
	StreamableHTTPPort *float64 `json:"streamableHttpPort,omitempty" tf:"streamable_http_port,omitempty"`

	// Streamable-HTTP MCP server URL override.
	StreamableHTTPURL *string `json:"streamableHttpUrl,omitempty" tf:"streamable_http_url,omitempty"`

	// Enable if the server publishes OAuth metadata at /.well-known/oauth-authorization-server for automatic endpoint discovery. Defaults to `false` (matching the backend default).
	SupportsResourceMetadata *bool `json:"supportsResourceMetadata,omitempty" tf:"supports_resource_metadata,omitempty"`

	// Custom OAuth token endpoint URL.
	TokenEndpoint *string `json:"tokenEndpoint,omitempty" tf:"token_endpoint,omitempty"`

	// Override for the `.well-known` discovery document URL.
	WellKnownURL *string `json:"wellKnownUrl,omitempty" tf:"well_known_url,omitempty"`
}

type OauthConfigObservation struct {

	// Environment variable name to inject the acquired access token into.
	AccessTokenEnvVar *string `json:"accessTokenEnvVar,omitempty" tf:"access_token_env_var,omitempty"`

	// `aud` claim to request when performing token exchange.
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// Override for the OAuth authorization server root URL.
	AuthServerURL *string `json:"authServerUrl,omitempty" tf:"auth_server_url,omitempty"`

	// Custom OAuth authorization endpoint URL
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty" tf:"authorization_endpoint,omitempty"`

	// Prompt the installer through an interactive browser auth flow.
	BrowserAuth *bool `json:"browserAuth,omitempty" tf:"browser_auth,omitempty"`

	// OAuth Client ID. Leave empty if the server supports dynamic client registration.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// Scopes requested by default when the server doesn't advertise its own.
	DefaultScopes []*string `json:"defaultScopes,omitempty" tf:"default_scopes,omitempty"`

	// Treat the server as a generic OAuth provider (skip vendor-specific probes).
	GenericOauth *bool `json:"genericOauth,omitempty" tf:"generic_oauth,omitempty"`

	// OAuth grant type. One of `authorization_code`, `client_credentials`.
	GrantType *string `json:"grantType,omitempty" tf:"grant_type,omitempty"`

	// Human-readable name of the OAuth provider for display.
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// Comma-separated list of redirect URIs
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// Route OAuth redirects through the Archestra proxy.
	RequiresProxy *bool `json:"requiresProxy,omitempty" tf:"requires_proxy,omitempty"`

	// URL of the protected-resource metadata document.
	ResourceMetadataURL *string `json:"resourceMetadataUrl,omitempty" tf:"resource_metadata_url,omitempty"`

	// List of OAuth scopes to request (e.g., ['read', 'write'])
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// Streamable-HTTP MCP server port override. Range 0..65535.
	StreamableHTTPPort *float64 `json:"streamableHttpPort,omitempty" tf:"streamable_http_port,omitempty"`

	// Streamable-HTTP MCP server URL override.
	StreamableHTTPURL *string `json:"streamableHttpUrl,omitempty" tf:"streamable_http_url,omitempty"`

	// Enable if the server publishes OAuth metadata at /.well-known/oauth-authorization-server for automatic endpoint discovery. Defaults to `false` (matching the backend default).
	SupportsResourceMetadata *bool `json:"supportsResourceMetadata,omitempty" tf:"supports_resource_metadata,omitempty"`

	// Custom OAuth token endpoint URL.
	TokenEndpoint *string `json:"tokenEndpoint,omitempty" tf:"token_endpoint,omitempty"`

	// Override for the `.well-known` discovery document URL.
	WellKnownURL *string `json:"wellKnownUrl,omitempty" tf:"well_known_url,omitempty"`
}

type OauthConfigParameters struct {

	// Environment variable name to inject the acquired access token into.
	// +kubebuilder:validation:Optional
	AccessTokenEnvVar *string `json:"accessTokenEnvVar,omitempty" tf:"access_token_env_var,omitempty"`

	// `aud` claim to request when performing token exchange.
	// +kubebuilder:validation:Optional
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// Override for the OAuth authorization server root URL.
	// +kubebuilder:validation:Optional
	AuthServerURL *string `json:"authServerUrl,omitempty" tf:"auth_server_url,omitempty"`

	// Custom OAuth authorization endpoint URL
	// +kubebuilder:validation:Optional
	AuthorizationEndpoint *string `json:"authorizationEndpoint,omitempty" tf:"authorization_endpoint,omitempty"`

	// Prompt the installer through an interactive browser auth flow.
	// +kubebuilder:validation:Optional
	BrowserAuth *bool `json:"browserAuth,omitempty" tf:"browser_auth,omitempty"`

	// OAuth Client ID. Leave empty if the server supports dynamic client registration.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// OAuth Client Secret (optional)
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v1.LocalSecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// Scopes requested by default when the server doesn't advertise its own.
	// +kubebuilder:validation:Optional
	DefaultScopes []*string `json:"defaultScopes,omitempty" tf:"default_scopes,omitempty"`

	// Treat the server as a generic OAuth provider (skip vendor-specific probes).
	// +kubebuilder:validation:Optional
	GenericOauth *bool `json:"genericOauth,omitempty" tf:"generic_oauth,omitempty"`

	// OAuth grant type. One of `authorization_code`, `client_credentials`.
	// +kubebuilder:validation:Optional
	GrantType *string `json:"grantType,omitempty" tf:"grant_type,omitempty"`

	// Human-readable name of the OAuth provider for display.
	// +kubebuilder:validation:Optional
	ProviderName *string `json:"providerName,omitempty" tf:"provider_name,omitempty"`

	// Comma-separated list of redirect URIs
	// +kubebuilder:validation:Optional
	RedirectUris []*string `json:"redirectUris" tf:"redirect_uris,omitempty"`

	// Route OAuth redirects through the Archestra proxy.
	// +kubebuilder:validation:Optional
	RequiresProxy *bool `json:"requiresProxy,omitempty" tf:"requires_proxy,omitempty"`

	// URL of the protected-resource metadata document.
	// +kubebuilder:validation:Optional
	ResourceMetadataURL *string `json:"resourceMetadataUrl,omitempty" tf:"resource_metadata_url,omitempty"`

	// List of OAuth scopes to request (e.g., ['read', 'write'])
	// +kubebuilder:validation:Optional
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// Streamable-HTTP MCP server port override. Range 0..65535.
	// +kubebuilder:validation:Optional
	StreamableHTTPPort *float64 `json:"streamableHttpPort,omitempty" tf:"streamable_http_port,omitempty"`

	// Streamable-HTTP MCP server URL override.
	// +kubebuilder:validation:Optional
	StreamableHTTPURL *string `json:"streamableHttpUrl,omitempty" tf:"streamable_http_url,omitempty"`

	// Enable if the server publishes OAuth metadata at /.well-known/oauth-authorization-server for automatic endpoint discovery. Defaults to `false` (matching the backend default).
	// +kubebuilder:validation:Optional
	SupportsResourceMetadata *bool `json:"supportsResourceMetadata,omitempty" tf:"supports_resource_metadata,omitempty"`

	// Custom OAuth token endpoint URL.
	// +kubebuilder:validation:Optional
	TokenEndpoint *string `json:"tokenEndpoint,omitempty" tf:"token_endpoint,omitempty"`

	// Override for the `.well-known` discovery document URL.
	// +kubebuilder:validation:Optional
	WellKnownURL *string `json:"wellKnownUrl,omitempty" tf:"well_known_url,omitempty"`
}

type RegistryCatalogItemInitParameters struct {

	// Description of the authentication requirements
	AuthDescription *string `json:"authDescription,omitempty" tf:"auth_description,omitempty"`

	AuthFields []AuthFieldsInitParameters `json:"authFields,omitempty" tf:"auth_fields,omitempty"`

	// UUID of a stored secret holding the OAuth client secret. Mutually exclusive with inline `oauth_config.client_secret`. Computed when the backend auto-creates a BYOS vault reference.
	ClientSecretID *string `json:"clientSecretId,omitempty" tf:"client_secret_id,omitempty"`

	// Custom Kubernetes deployment YAML for the MCP server
	DeploymentSpecYaml *string `json:"deploymentSpecYaml,omitempty" tf:"deployment_spec_yaml,omitempty"`

	// Description of the MCP server
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// URL to the MCP server documentation
	DocsURL *string `json:"docsUrl,omitempty" tf:"docs_url,omitempty"`

	EnterpriseManagedConfig *EnterpriseManagedConfigInitParameters `json:"enterpriseManagedConfig,omitempty" tf:"enterprise_managed_config,omitempty"`

	// Icon string for the MCP server
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// Installation command for the MCP server (e.g., npm install -g @example/mcp-server)
	InstallationCommand *string `json:"installationCommand,omitempty" tf:"installation_command,omitempty"`

	// Installation instructions text for the MCP server
	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	Labels []LabelsInitParameters `json:"labels,omitempty" tf:"labels,omitempty"`

	LocalConfig *LocalConfigInitParameters `json:"localConfig,omitempty" tf:"local_config,omitempty"`

	// UUID of a stored secret holding local_config environment values. Computed when the backend auto-creates a BYOS vault reference.
	LocalConfigSecretID *string `json:"localConfigSecretId,omitempty" tf:"local_config_secret_id,omitempty"`

	// BYOS vault key for local_config secrets.
	LocalConfigVaultKey *string `json:"localConfigVaultKey,omitempty" tf:"local_config_vault_key,omitempty"`

	// BYOS vault path for local_config secrets.
	LocalConfigVaultPath *string `json:"localConfigVaultPath,omitempty" tf:"local_config_vault_path,omitempty"`

	// The name of the MCP server
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// BYOS vault key for the OAuth client secret.
	OauthClientSecretVaultKey *string `json:"oauthClientSecretVaultKey,omitempty" tf:"oauth_client_secret_vault_key,omitempty"`

	// BYOS vault path for the OAuth client secret.
	OauthClientSecretVaultPath *string `json:"oauthClientSecretVaultPath,omitempty" tf:"oauth_client_secret_vault_path,omitempty"`

	RemoteConfig *RemoteConfigInitParameters `json:"remoteConfig,omitempty" tf:"remote_config,omitempty"`

	// Repository URL for the MCP server
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Whether the MCP server requires authentication
	RequiresAuth *bool `json:"requiresAuth,omitempty" tf:"requires_auth,omitempty"`

	// Visibility scope for the MCP server catalog item (e.g., 'personal', 'team', 'org')
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// Team IDs that have access to this MCP server
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`

	UserConfig map[string]UserConfigInitParameters `json:"userConfig,omitempty" tf:"user_config,omitempty"`

	// Version string for the MCP server
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type RegistryCatalogItemObservation struct {

	// Description of the authentication requirements
	AuthDescription *string `json:"authDescription,omitempty" tf:"auth_description,omitempty"`

	AuthFields []AuthFieldsObservation `json:"authFields,omitempty" tf:"auth_fields,omitempty"`

	// UUID of a stored secret holding the OAuth client secret. Mutually exclusive with inline `oauth_config.client_secret`. Computed when the backend auto-creates a BYOS vault reference.
	ClientSecretID *string `json:"clientSecretId,omitempty" tf:"client_secret_id,omitempty"`

	// Custom Kubernetes deployment YAML for the MCP server
	DeploymentSpecYaml *string `json:"deploymentSpecYaml,omitempty" tf:"deployment_spec_yaml,omitempty"`

	// Description of the MCP server
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// URL to the MCP server documentation
	DocsURL *string `json:"docsUrl,omitempty" tf:"docs_url,omitempty"`

	EnterpriseManagedConfig *EnterpriseManagedConfigObservation `json:"enterpriseManagedConfig,omitempty" tf:"enterprise_managed_config,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Icon string for the MCP server
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// Installation command for the MCP server (e.g., npm install -g @example/mcp-server)
	InstallationCommand *string `json:"installationCommand,omitempty" tf:"installation_command,omitempty"`

	// Installation instructions text for the MCP server
	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	Labels []LabelsObservation `json:"labels,omitempty" tf:"labels,omitempty"`

	LocalConfig *LocalConfigObservation `json:"localConfig,omitempty" tf:"local_config,omitempty"`

	// UUID of a stored secret holding local_config environment values. Computed when the backend auto-creates a BYOS vault reference.
	LocalConfigSecretID *string `json:"localConfigSecretId,omitempty" tf:"local_config_secret_id,omitempty"`

	// BYOS vault key for local_config secrets.
	LocalConfigVaultKey *string `json:"localConfigVaultKey,omitempty" tf:"local_config_vault_key,omitempty"`

	// BYOS vault path for local_config secrets.
	LocalConfigVaultPath *string `json:"localConfigVaultPath,omitempty" tf:"local_config_vault_path,omitempty"`

	// The name of the MCP server
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// BYOS vault key for the OAuth client secret.
	OauthClientSecretVaultKey *string `json:"oauthClientSecretVaultKey,omitempty" tf:"oauth_client_secret_vault_key,omitempty"`

	// BYOS vault path for the OAuth client secret.
	OauthClientSecretVaultPath *string `json:"oauthClientSecretVaultPath,omitempty" tf:"oauth_client_secret_vault_path,omitempty"`

	RemoteConfig *RemoteConfigObservation `json:"remoteConfig,omitempty" tf:"remote_config,omitempty"`

	// Repository URL for the MCP server
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Whether the MCP server requires authentication
	RequiresAuth *bool `json:"requiresAuth,omitempty" tf:"requires_auth,omitempty"`

	// Visibility scope for the MCP server catalog item (e.g., 'personal', 'team', 'org')
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// Team IDs that have access to this MCP server
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`

	UserConfig map[string]UserConfigObservation `json:"userConfig,omitempty" tf:"user_config,omitempty"`

	// Version string for the MCP server
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type RegistryCatalogItemParameters struct {

	// Description of the authentication requirements
	// +kubebuilder:validation:Optional
	AuthDescription *string `json:"authDescription,omitempty" tf:"auth_description,omitempty"`

	// +kubebuilder:validation:Optional
	AuthFields []AuthFieldsParameters `json:"authFields,omitempty" tf:"auth_fields,omitempty"`

	// UUID of a stored secret holding the OAuth client secret. Mutually exclusive with inline `oauth_config.client_secret`. Computed when the backend auto-creates a BYOS vault reference.
	// +kubebuilder:validation:Optional
	ClientSecretID *string `json:"clientSecretId,omitempty" tf:"client_secret_id,omitempty"`

	// Custom Kubernetes deployment YAML for the MCP server
	// +kubebuilder:validation:Optional
	DeploymentSpecYaml *string `json:"deploymentSpecYaml,omitempty" tf:"deployment_spec_yaml,omitempty"`

	// Description of the MCP server
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// URL to the MCP server documentation
	// +kubebuilder:validation:Optional
	DocsURL *string `json:"docsUrl,omitempty" tf:"docs_url,omitempty"`

	// +kubebuilder:validation:Optional
	EnterpriseManagedConfig *EnterpriseManagedConfigParameters `json:"enterpriseManagedConfig,omitempty" tf:"enterprise_managed_config,omitempty"`

	// Icon string for the MCP server
	// +kubebuilder:validation:Optional
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// Installation command for the MCP server (e.g., npm install -g @example/mcp-server)
	// +kubebuilder:validation:Optional
	InstallationCommand *string `json:"installationCommand,omitempty" tf:"installation_command,omitempty"`

	// Installation instructions text for the MCP server
	// +kubebuilder:validation:Optional
	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	// +kubebuilder:validation:Optional
	Labels []LabelsParameters `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	LocalConfig *LocalConfigParameters `json:"localConfig,omitempty" tf:"local_config,omitempty"`

	// UUID of a stored secret holding local_config environment values. Computed when the backend auto-creates a BYOS vault reference.
	// +kubebuilder:validation:Optional
	LocalConfigSecretID *string `json:"localConfigSecretId,omitempty" tf:"local_config_secret_id,omitempty"`

	// BYOS vault key for local_config secrets.
	// +kubebuilder:validation:Optional
	LocalConfigVaultKey *string `json:"localConfigVaultKey,omitempty" tf:"local_config_vault_key,omitempty"`

	// BYOS vault path for local_config secrets.
	// +kubebuilder:validation:Optional
	LocalConfigVaultPath *string `json:"localConfigVaultPath,omitempty" tf:"local_config_vault_path,omitempty"`

	// The name of the MCP server
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// BYOS vault key for the OAuth client secret.
	// +kubebuilder:validation:Optional
	OauthClientSecretVaultKey *string `json:"oauthClientSecretVaultKey,omitempty" tf:"oauth_client_secret_vault_key,omitempty"`

	// BYOS vault path for the OAuth client secret.
	// +kubebuilder:validation:Optional
	OauthClientSecretVaultPath *string `json:"oauthClientSecretVaultPath,omitempty" tf:"oauth_client_secret_vault_path,omitempty"`

	// +kubebuilder:validation:Optional
	RemoteConfig *RemoteConfigParameters `json:"remoteConfig,omitempty" tf:"remote_config,omitempty"`

	// Repository URL for the MCP server
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// Whether the MCP server requires authentication
	// +kubebuilder:validation:Optional
	RequiresAuth *bool `json:"requiresAuth,omitempty" tf:"requires_auth,omitempty"`

	// Visibility scope for the MCP server catalog item (e.g., 'personal', 'team', 'org')
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// Team IDs that have access to this MCP server
	// +kubebuilder:validation:Optional
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`

	// +kubebuilder:validation:Optional
	UserConfig map[string]UserConfigParameters `json:"userConfig,omitempty" tf:"user_config,omitempty"`

	// Version string for the MCP server
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type RemoteConfigInitParameters struct {
	OauthConfig *OauthConfigInitParameters `json:"oauthConfig,omitempty" tf:"oauth_config,omitempty"`

	// The URL of the remote MCP server (e.g., https://api.githubcopilot.com/mcp/)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RemoteConfigObservation struct {
	OauthConfig *OauthConfigObservation `json:"oauthConfig,omitempty" tf:"oauth_config,omitempty"`

	// The URL of the remote MCP server (e.g., https://api.githubcopilot.com/mcp/)
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RemoteConfigParameters struct {

	// +kubebuilder:validation:Optional
	OauthConfig *OauthConfigParameters `json:"oauthConfig,omitempty" tf:"oauth_config,omitempty"`

	// The URL of the remote MCP server (e.g., https://api.githubcopilot.com/mcp/)
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type UserConfigInitParameters struct {

	// Default value. Use `jsonencode(...)` to encode non-string defaults (number, bool, or []string). Plain strings may be provided as-is.
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Description of the field shown to the installer.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// HTTP header name to bind this value to when installing a remote server.
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Maximum value (for numeric fields).
	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	// Minimum value (for numeric fields).
	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`

	// Whether multiple values may be supplied.
	Multiple *bool `json:"multiple,omitempty" tf:"multiple,omitempty"`

	// Whether to prompt the user for this value during installation.
	PromptOnInstallation *bool `json:"promptOnInstallation,omitempty" tf:"prompt_on_installation,omitempty"`

	// Whether the installer must supply this field.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// If true, the value is redacted in logs and UI.
	Sensitive *bool `json:"sensitive,omitempty" tf:"sensitive,omitempty"`

	// Human-readable field title shown to the installer.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// Field type. One of `string`, `number`, `boolean`, `file`, `directory`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type UserConfigObservation struct {

	// Default value. Use `jsonencode(...)` to encode non-string defaults (number, bool, or []string). Plain strings may be provided as-is.
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Description of the field shown to the installer.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// HTTP header name to bind this value to when installing a remote server.
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Maximum value (for numeric fields).
	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	// Minimum value (for numeric fields).
	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`

	// Whether multiple values may be supplied.
	Multiple *bool `json:"multiple,omitempty" tf:"multiple,omitempty"`

	// Whether to prompt the user for this value during installation.
	PromptOnInstallation *bool `json:"promptOnInstallation,omitempty" tf:"prompt_on_installation,omitempty"`

	// Whether the installer must supply this field.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// If true, the value is redacted in logs and UI.
	Sensitive *bool `json:"sensitive,omitempty" tf:"sensitive,omitempty"`

	// Human-readable field title shown to the installer.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// Field type. One of `string`, `number`, `boolean`, `file`, `directory`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type UserConfigParameters struct {

	// Default value. Use `jsonencode(...)` to encode non-string defaults (number, bool, or []string). Plain strings may be provided as-is.
	// +kubebuilder:validation:Optional
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// Description of the field shown to the installer.
	// +kubebuilder:validation:Optional
	Description *string `json:"description" tf:"description,omitempty"`

	// HTTP header name to bind this value to when installing a remote server.
	// +kubebuilder:validation:Optional
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`

	// Maximum value (for numeric fields).
	// +kubebuilder:validation:Optional
	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	// Minimum value (for numeric fields).
	// +kubebuilder:validation:Optional
	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`

	// Whether multiple values may be supplied.
	// +kubebuilder:validation:Optional
	Multiple *bool `json:"multiple,omitempty" tf:"multiple,omitempty"`

	// Whether to prompt the user for this value during installation.
	// +kubebuilder:validation:Optional
	PromptOnInstallation *bool `json:"promptOnInstallation,omitempty" tf:"prompt_on_installation,omitempty"`

	// Whether the installer must supply this field.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// If true, the value is redacted in logs and UI.
	// +kubebuilder:validation:Optional
	Sensitive *bool `json:"sensitive,omitempty" tf:"sensitive,omitempty"`

	// Human-readable field title shown to the installer.
	// +kubebuilder:validation:Optional
	Title *string `json:"title" tf:"title,omitempty"`

	// Field type. One of `string`, `number`, `boolean`, `file`, `directory`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

// RegistryCatalogItemSpec defines the desired state of RegistryCatalogItem
type RegistryCatalogItemSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RegistryCatalogItemParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RegistryCatalogItemInitParameters `json:"initProvider,omitempty"`
}

// RegistryCatalogItemStatus defines the observed state of RegistryCatalogItem.
type RegistryCatalogItemStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RegistryCatalogItemObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RegistryCatalogItem is the Schema for the RegistryCatalogItems API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,archestra}
type RegistryCatalogItem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RegistryCatalogItemSpec   `json:"spec"`
	Status RegistryCatalogItemStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RegistryCatalogItemList contains a list of RegistryCatalogItems
type RegistryCatalogItemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RegistryCatalogItem `json:"items"`
}

// Repository type metadata.
var (
	RegistryCatalogItem_Kind             = "RegistryCatalogItem"
	RegistryCatalogItem_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RegistryCatalogItem_Kind}.String()
	RegistryCatalogItem_KindAPIVersion   = RegistryCatalogItem_Kind + "." + CRDGroupVersion.String()
	RegistryCatalogItem_GroupVersionKind = CRDGroupVersion.WithKind(RegistryCatalogItem_Kind)
)

func init() {
	SchemeBuilder.Register(&RegistryCatalogItem{}, &RegistryCatalogItemList{})
}
