// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AssignedAgentsInitParameters struct {
}

type AssignedAgentsObservation struct {

	// Agent UUID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Agent name (the agent's `name` field on `archestra_agent` / `archestra_llm_proxy` / `archestra_mcp_gateway`).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AssignedAgentsParameters struct {
}

type ServerInstallationInitParameters struct {

	// Personal access token for the MCP server
	AccessTokenSecretRef *v1.LocalSecretKeySelector `json:"accessTokenSecretRef,omitempty" tf:"-"`

	// Agent IDs to auto-assign tools to on install
	AgentIds []*string `json:"agentIds,omitempty" tf:"agent_ids,omitempty"`

	// Catalog item ID (UUID of the `archestra_mcp_registry_catalog_item` resource) this installation is based on.
	// +crossplane:generate:reference:type=github.com/archestra-ai/provider-archestra/apis/namespaced/mcp/v1alpha1.RegistryCatalogItem
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a RegistryCatalogItem in mcp to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v1.NamespacedReference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a RegistryCatalogItem in mcp to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v1.NamespacedSelector `json:"catalogIdSelector,omitempty" tf:"-"`

	// Environment variable values for the MCP server installation
	// +mapType=granular
	EnvironmentValues map[string]*string `json:"environmentValues,omitempty" tf:"environment_values,omitempty"`

	// When true, environment_values and user_config_values are treated as vault references
	IsByosVault *bool `json:"isByosVault,omitempty" tf:"is_byos_vault,omitempty"`

	// The name of the MCP server installation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Secret UUID for the MCP server installation. Set explicitly to reference a pre-created secret; otherwise the backend creates one when `user_config_values` is set and writes the resulting UUID back here.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// Kubernetes service account override for the MCP server pod
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Team ID for team-scoped installations
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// User configuration field values for the MCP server installation
	// +mapType=granular
	UserConfigValues map[string]*string `json:"userConfigValues,omitempty" tf:"user_config_values,omitempty"`
}

type ServerInstallationObservation struct {

	// Agent IDs to auto-assign tools to on install
	AgentIds []*string `json:"agentIds,omitempty" tf:"agent_ids,omitempty"`

	// Catalog item ID (UUID of the `archestra_mcp_registry_catalog_item` resource) this installation is based on.
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// The actual name of the MCP server installation as returned by the API. The API may append a suffix to ensure uniqueness.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Environment variable values for the MCP server installation
	// +mapType=granular
	EnvironmentValues map[string]*string `json:"environmentValues,omitempty" tf:"environment_values,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// When true, environment_values and user_config_values are treated as vault references
	IsByosVault *bool `json:"isByosVault,omitempty" tf:"is_byos_vault,omitempty"`

	// The name of the MCP server installation.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Secret UUID for the MCP server installation. Set explicitly to reference a pre-created secret; otherwise the backend creates one when `user_config_values` is set and writes the resulting UUID back here.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// Kubernetes service account override for the MCP server pod
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Team ID for team-scoped installations
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Lookup table from each tool's wire name (`<server>__<short>`) to its bare tool UUID — same data as `tools[*].id` but keyed for one-line lookups. Null while tools are still being discovered.
	// +mapType=granular
	ToolIDByName map[string]*string `json:"toolIdByName,omitempty" tf:"tool_id_by_name,omitempty"`

	Tools []ToolsObservation `json:"tools,omitempty" tf:"tools,omitempty"`

	// User configuration field values for the MCP server installation
	// +mapType=granular
	UserConfigValues map[string]*string `json:"userConfigValues,omitempty" tf:"user_config_values,omitempty"`
}

type ServerInstallationParameters struct {

	// Personal access token for the MCP server
	// +kubebuilder:validation:Optional
	AccessTokenSecretRef *v1.LocalSecretKeySelector `json:"accessTokenSecretRef,omitempty" tf:"-"`

	// Agent IDs to auto-assign tools to on install
	// +kubebuilder:validation:Optional
	AgentIds []*string `json:"agentIds,omitempty" tf:"agent_ids,omitempty"`

	// Catalog item ID (UUID of the `archestra_mcp_registry_catalog_item` resource) this installation is based on.
	// +crossplane:generate:reference:type=github.com/archestra-ai/provider-archestra/apis/namespaced/mcp/v1alpha1.RegistryCatalogItem
	// +kubebuilder:validation:Optional
	CatalogID *string `json:"catalogId,omitempty" tf:"catalog_id,omitempty"`

	// Reference to a RegistryCatalogItem in mcp to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDRef *v1.NamespacedReference `json:"catalogIdRef,omitempty" tf:"-"`

	// Selector for a RegistryCatalogItem in mcp to populate catalogId.
	// +kubebuilder:validation:Optional
	CatalogIDSelector *v1.NamespacedSelector `json:"catalogIdSelector,omitempty" tf:"-"`

	// Environment variable values for the MCP server installation
	// +kubebuilder:validation:Optional
	// +mapType=granular
	EnvironmentValues map[string]*string `json:"environmentValues,omitempty" tf:"environment_values,omitempty"`

	// When true, environment_values and user_config_values are treated as vault references
	// +kubebuilder:validation:Optional
	IsByosVault *bool `json:"isByosVault,omitempty" tf:"is_byos_vault,omitempty"`

	// The name of the MCP server installation.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Secret UUID for the MCP server installation. Set explicitly to reference a pre-created secret; otherwise the backend creates one when `user_config_values` is set and writes the resulting UUID back here.
	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// Kubernetes service account override for the MCP server pod
	// +kubebuilder:validation:Optional
	ServiceAccount *string `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`

	// Team ID for team-scoped installations
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// User configuration field values for the MCP server installation
	// +kubebuilder:validation:Optional
	// +mapType=granular
	UserConfigValues map[string]*string `json:"userConfigValues,omitempty" tf:"user_config_values,omitempty"`
}

type ToolsInitParameters struct {
}

type ToolsObservation struct {

	// Number of agents this tool is currently assigned to. Quick visibility without fetching the full assignment list.
	AssignedAgentCount *float64 `json:"assignedAgentCount,omitempty" tf:"assigned_agent_count,omitempty"`

	AssignedAgents []AssignedAgentsObservation `json:"assignedAgents,omitempty" tf:"assigned_agents,omitempty"`

	// RFC 3339 timestamp of when the tool was first registered with the backend.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Human-readable description as advertised by the MCP server. May be null.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Tool UUID. Use as `tool_id` on `archestra_tool_invocation_policy` / `archestra_trusted_data_policy`.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Tool name (the MCP server's own identifier — stable across installs of the same catalog item).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// JSON Schema for the tool's input parameters, encoded as a JSON string. Use `jsondecode(t.parameters)` to introspect required fields, types, etc. for validation or downstream codegen.
	Parameters *string `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type ToolsParameters struct {
}

// ServerInstallationSpec defines the desired state of ServerInstallation
type ServerInstallationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServerInstallationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerInstallationInitParameters `json:"initProvider,omitempty"`
}

// ServerInstallationStatus defines the observed state of ServerInstallation.
type ServerInstallationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerInstallationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServerInstallation is the Schema for the ServerInstallations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,archestra}
type ServerInstallation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ServerInstallationSpec   `json:"spec"`
	Status ServerInstallationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerInstallationList contains a list of ServerInstallations
type ServerInstallationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServerInstallation `json:"items"`
}

// Repository type metadata.
var (
	ServerInstallation_Kind             = "ServerInstallation"
	ServerInstallation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServerInstallation_Kind}.String()
	ServerInstallation_KindAPIVersion   = ServerInstallation_Kind + "." + CRDGroupVersion.String()
	ServerInstallation_GroupVersionKind = CRDGroupVersion.WithKind(ServerInstallation_Kind)
)

func init() {
	SchemeBuilder.Register(&ServerInstallation{}, &ServerInstallationList{})
}
