name: Setup Go Environment
description: Set up Go environment for Terraform provider development and builds

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
