name: Setup Terraform
description: Set up Terraform environment

runs:
  using: composite
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: "1.13.4"
