//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInvocationPolicyDefault) DeepCopyInto(out *ToolInvocationPolicyDefault) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInvocationPolicyDefault.
func (in *ToolInvocationPolicyDefault) DeepCopy() *ToolInvocationPolicyDefault {
	if in == nil {
		return nil
	}
	out := new(ToolInvocationPolicyDefault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolInvocationPolicyDefault) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInvocationPolicyDefaultInitParameters) DeepCopyInto(out *ToolInvocationPolicyDefaultInitParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ToolIds != nil {
		in, out := &in.ToolIds, &out.ToolIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInvocationPolicyDefaultInitParameters.
func (in *ToolInvocationPolicyDefaultInitParameters) DeepCopy() *ToolInvocationPolicyDefaultInitParameters {
	if in == nil {
		return nil
	}
	out := new(ToolInvocationPolicyDefaultInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInvocationPolicyDefaultList) DeepCopyInto(out *ToolInvocationPolicyDefaultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToolInvocationPolicyDefault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInvocationPolicyDefaultList.
func (in *ToolInvocationPolicyDefaultList) DeepCopy() *ToolInvocationPolicyDefaultList {
	if in == nil {
		return nil
	}
	out := new(ToolInvocationPolicyDefaultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolInvocationPolicyDefaultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInvocationPolicyDefaultObservation) DeepCopyInto(out *ToolInvocationPolicyDefaultObservation) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ToolIds != nil {
		in, out := &in.ToolIds, &out.ToolIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInvocationPolicyDefaultObservation.
func (in *ToolInvocationPolicyDefaultObservation) DeepCopy() *ToolInvocationPolicyDefaultObservation {
	if in == nil {
		return nil
	}
	out := new(ToolInvocationPolicyDefaultObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInvocationPolicyDefaultParameters) DeepCopyInto(out *ToolInvocationPolicyDefaultParameters) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.ToolIds != nil {
		in, out := &in.ToolIds, &out.ToolIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInvocationPolicyDefaultParameters.
func (in *ToolInvocationPolicyDefaultParameters) DeepCopy() *ToolInvocationPolicyDefaultParameters {
	if in == nil {
		return nil
	}
	out := new(ToolInvocationPolicyDefaultParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInvocationPolicyDefaultSpec) DeepCopyInto(out *ToolInvocationPolicyDefaultSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInvocationPolicyDefaultSpec.
func (in *ToolInvocationPolicyDefaultSpec) DeepCopy() *ToolInvocationPolicyDefaultSpec {
	if in == nil {
		return nil
	}
	out := new(ToolInvocationPolicyDefaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolInvocationPolicyDefaultStatus) DeepCopyInto(out *ToolInvocationPolicyDefaultStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolInvocationPolicyDefaultStatus.
func (in *ToolInvocationPolicyDefaultStatus) DeepCopy() *ToolInvocationPolicyDefaultStatus {
	if in == nil {
		return nil
	}
	out := new(ToolInvocationPolicyDefaultStatus)
	in.DeepCopyInto(out)
	return out
}
