// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ToolInvocationPolicyDefaultInitParameters struct {

	// Default action when no conditional policy matches. One of:
	//
	// - `allow_when_context_is_untrusted` — let the call through even with untrusted context (most permissive).
	// - `block_when_context_is_untrusted` — let the call through only when context is trusted.
	// - `require_approval` — surface for human approval before executing.
	// - `block_always` — never execute (most restrictive).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// Set of bare tool UUIDs to apply the default policy to. Typically `[for t in archestra_mcp_server_installation.<n>.tools : t.id]`.
	// +listType=set
	ToolIds []*string `json:"toolIds,omitempty" tf:"tool_ids,omitempty"`
}

type ToolInvocationPolicyDefaultObservation struct {

	// Default action when no conditional policy matches. One of:
	//
	// - `allow_when_context_is_untrusted` — let the call through even with untrusted context (most permissive).
	// - `block_when_context_is_untrusted` — let the call through only when context is trusted.
	// - `require_approval` — surface for human approval before executing.
	// - `block_always` — never execute (most restrictive).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Set of bare tool UUIDs to apply the default policy to. Typically `[for t in archestra_mcp_server_installation.<n>.tools : t.id]`.
	// +listType=set
	ToolIds []*string `json:"toolIds,omitempty" tf:"tool_ids,omitempty"`
}

type ToolInvocationPolicyDefaultParameters struct {

	// Default action when no conditional policy matches. One of:
	//
	// - `allow_when_context_is_untrusted` — let the call through even with untrusted context (most permissive).
	// - `block_when_context_is_untrusted` — let the call through only when context is trusted.
	// - `require_approval` — surface for human approval before executing.
	// - `block_always` — never execute (most restrictive).
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// Set of bare tool UUIDs to apply the default policy to. Typically `[for t in archestra_mcp_server_installation.<n>.tools : t.id]`.
	// +kubebuilder:validation:Optional
	// +listType=set
	ToolIds []*string `json:"toolIds,omitempty" tf:"tool_ids,omitempty"`
}

// ToolInvocationPolicyDefaultSpec defines the desired state of ToolInvocationPolicyDefault
type ToolInvocationPolicyDefaultSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ToolInvocationPolicyDefaultParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToolInvocationPolicyDefaultInitParameters `json:"initProvider,omitempty"`
}

// ToolInvocationPolicyDefaultStatus defines the observed state of ToolInvocationPolicyDefault.
type ToolInvocationPolicyDefaultStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToolInvocationPolicyDefaultObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToolInvocationPolicyDefault is the Schema for the ToolInvocationPolicyDefaults API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,archestra}
type ToolInvocationPolicyDefault struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.action) || (has(self.initProvider) && has(self.initProvider.action))",message="spec.forProvider.action is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.toolIds) || (has(self.initProvider) && has(self.initProvider.toolIds))",message="spec.forProvider.toolIds is a required parameter"
	Spec   ToolInvocationPolicyDefaultSpec   `json:"spec"`
	Status ToolInvocationPolicyDefaultStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToolInvocationPolicyDefaultList contains a list of ToolInvocationPolicyDefaults
type ToolInvocationPolicyDefaultList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToolInvocationPolicyDefault `json:"items"`
}

// Repository type metadata.
var (
	ToolInvocationPolicyDefault_Kind             = "ToolInvocationPolicyDefault"
	ToolInvocationPolicyDefault_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToolInvocationPolicyDefault_Kind}.String()
	ToolInvocationPolicyDefault_KindAPIVersion   = ToolInvocationPolicyDefault_Kind + "." + CRDGroupVersion.String()
	ToolInvocationPolicyDefault_GroupVersionKind = CRDGroupVersion.WithKind(ToolInvocationPolicyDefault_Kind)
)

func init() {
	SchemeBuilder.Register(&ToolInvocationPolicyDefault{}, &ToolInvocationPolicyDefaultList{})
}
