name: Linting and Tests

on:
  workflow_call:

jobs:
  linting-and-tests:
    name: Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup go
        uses: ./.github/actions/setup-go

      - name: Linting and formatting
        run: |
          make lint
          make fmt

      - name: Tests
        run: |
          make test

          # NOTE: for now don't run "acceptance tests" because the Terraform proposed pattern for these is that
          # they create real resources and we don't have a way for now to create the local environment to do so
          # make testacc

      - name: Build
        run: |
          # Can't run generate in CI because we don't have the OpenAPI spec available over HTTP
          # make generate
          make build
