name: Linting and Tests

on:
  workflow_call:

jobs:
  linting-and-tests:
    name: Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup go
        uses: ./.github/actions/setup-go

      - name: Ensure go mod is "tidy"
        run: go mod tidy -diff

      - name: Linting and formatting
        run: |
          make lint
          make fmt
          make generate

          if ! git diff --exit-code; then
            echo "🔴🔴🔴: There are uncommitted changes. Please run 'make lint', 'make fmt', and 'make generate' and commit the changes. 🔴🔴🔴"
            exit 1
          fi

      - name: Tests
        run: |
          make test

          # NOTE: for now don't run "acceptance tests" because the Terraform proposed pattern for these is that
          # they create real resources and we don't have a way for now to create the local environment to do so
          # make testacc

      - name: Build
        run: make build
